### ISSUE TITLE
script launchers for each session

### ISSUE THREAD

**Issue by drhuffman12** [CypherpunkArmory/UserLAnd#60] opened 2018-06-22 13:30 UTC
The UI lets you click to launch a session. I am requesting that each session can have script launchers of some sort; possibly something like bash file launcher. Or, combine the session and script launcher into something like a Dockerfile or Vagrantfile (or a UserLAndfile).

**Comment by lapsio** [comment] 2018-06-23 16:37
#56 I think it's related at this point

**Comment by AdamMatthewLTM** [comment] 2018-06-26 19:36
@drhuffman12 , 

Thank you for your request. I can confirm the developers will implement the ability to launch script files in future updates, and therefore will be flagging this thread as an 'enhancement' and request it be kept opened until further notice. If an update in regards to the time frame of said implementation is made available, I will post an update to this thread.

@lapsio , 
In regards to linking this particular thread to #56 , may I recommend this not be linked for the time being? My reasoning is that this thread is strictly a request for a feature implementation - however the thread you associated with this one is a question for a specific method of accessing the settings for dropbear.

If you feel these threads should still be linked/associated however, please reply here and I will associate them together.

Thank you for your understanding,

Adam

**Comment by lapsio** [comment] 2018-06-26 21:43
@AdamMatthewLTM 
This feature request is in a sense viable solution for my question regarding dropbear. Aka launcher scripts would significantly decrease necessity of having more flexible dropbear config due to ability to offload port forwarding, changing ports etc to launcher scripts that could for example autolauch socat or even second dropbear instance. That's basically why I linked but technically yes, they're not 1:1 equivalents. Just related.

**Comment by AdamMatthewLTM** [comment] 2018-10-04 16:45
I am now closing this issue for the following reason:

This feature is being implemented as of the closing of this thread. Application and script launchers will be made available in the UserLAnd app, with firefox being one of the first implementations.

I am suggesting all other issues _specifically addressing_ each individual application/startup script be filed under its own thread issue if any problems arise in the future.

Therefore, if you feel this particular thread should remain open please cite your reasoning with regards to the original enhancement suggestion (not app-specific) and I will re-open this ASAP.

Thank you all for your time and consideration,
-Adam

**Closed by AdamMatthewLTM** 2018-10-04 16:45 UTC
Labels: enhancement, question
