### ISSUE TITLE
Feature Request - [Install from ISO]

### ISSUE THREAD

**Issue by Pummelchen** [CypherpunkArmory/UserLAnd#896] opened 2019-06-14 14:26 UTC
# Describe the problem your feature request solves.
I noticed that UserLAnd does not give us a 100% native environment to run a full distribution, you merely emulate a file structure, where most things dont work when required. What we need is a way to install a real full Linux distribution from an ISO file we downloaded.

# Describe the solution you'd like 
Provide a solution where we can run real Linux distribution on an Android phone.

**Comment by Marcus0086** [comment] 2019-06-18 06:24
@Pummelchen What are you talking about? Its a chrooted environment. If you don't know what a chroot environment is then first research on it and then close this issue. ISO files really? You don't even know what a iso file is?

**Comment by corbinlc** [comment] 2019-06-18 06:42
@Marcus0086 we don't do flame wars here.

@Pummelchen there is a lot more working than just a file structure.  That being said, it is true that a few things don't work.  These are mostly because we 1) don't run as real root and 2) android is a little weird, but we emulate as much as we can.  We do have a plan to support running as the real root user (for people that have rooted their devices) later, which will help with 2).  Mounting an ISO would require us to run as real root.  There is no specific date that we will support running as real root.

I am going to make some high level issues, like "does not run as real root", that will discuss specific limitations and act as a place to collect and discuss these sorts of things without so many unique issues being opened.

**Comment by Marcus0086** [comment] 2019-06-18 18:12
@corbinlc Hey look first i am sorry if i offend someone and i think that you might have misunderstood me. Btw i was just asking @Pummelchen that chroots are way diff than ISO.

**Comment by corbinlc** [comment] 2019-06-20 01:37
I have just created a high level issue to discuss all the things that we cannot do unless we support running as a real root user, #910.
I am closing this one, but please follow #910 for updates, as I have added it to the list found there.  This is to avoid having too many open issues that all have the same root cause.
After we support running a real root user, the device owner will still have to root their device and give us permissions to run as real root.

**Closed by corbinlc** 2019-06-20 01:37 UTC
Labels: more-info-required
