### ISSUE TITLE
Couldn't extract file system

### ISSUE THREAD

**Issue by AboodiGamer** [CypherpunkArmory/UserLAnd#380] opened 2018-11-03 05:31 UTC
PRoot_Debug_Log:
[H[Jproot warning: can't sanitize binding "/data/user/0/tech.ula/files/2/tmp": No such file or directory
proot info: binding = /data/data/tech.ula/files/support/uptime:/proc/uptime
proot info: binding = /storage/emulated/0:/sdcard
proot info: binding = /data/data/tech.ula/files/2/support/ld.so.preload:/etc/ld.so.preload
proot info: binding = /data/data/tech.ula/files/2/support/userland_profile.sh:/etc/profile.d/userland_profile.sh
proot info: binding = /data/data/tech.ula/files/2/support/nosudo:/usr/local/bin/sudo
proot info: binding = /data/data/tech.ula/files/2/support:/support
proot info: binding = /:/host-rootfs
proot info: binding = /proc/24166/mounts:/etc/mtab
proot info: binding = /mnt
proot info: binding = /data
proot info: binding = /proc
proot info: binding = /dev
proot info: binding = /sys
proot info: binding = /data/data/tech.ula/files/2:/
proot info: vpid 1: translate("/" + "/support/extractFilesystem.sh")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/support/extractFilesystem.sh"
proot info: vpid 1: translate("/" + "/support/extractFilesystem.sh")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/support/extractFilesystem.sh"
proot info: glue rootfs = /data/data/tech.ula/files/2/support/proot-24166-guwwz9
proot info: exe = /support/extractFilesystem.sh
proot info: argv = /support/extractFilesystem.sh
proot info: initial cwd = /data/data/tech.ula/files/2
proot info: verbose level = 9
proot info: pid 24166: access to "/proc/24166/fd" (fd 3) won't be translated until closed
proot info: vpid 1: sysenter start: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0xf21a34bc) = 0x26 [0xff914890, 0]
proot info: vpid 1: sysenter end: prctl(0x26, 0x1, 0x0, 0x0, 0x0, 0xf21a34bc) = 0x26 [0xff914890, 0]
proot info: vpid 1: sysexit start: prctl(0x0, 0x1, 0x0, 0x0, 0x0, 0xf21a34bc) = 0x0 [0xff914890, 0]
proot info: vpid 1: sysexit end: prctl(0x0, 0x1, 0x0, 0x0, 0x0, 0xf21a34bc) = 0x0 [0xff914890, 0]
proot info: vpid 1: sysenter start: prctl(0x16, 0x2, 0xff9148b0, 0x0, 0x0, 0xf21a34bc) = 0x16 [0xff914890, 0]
proot info: vpid 1: sysenter end: prctl(0x16, 0x2, 0xff9148b0, 0x0, 0x0, 0xf21a34bc) = 0x16 [0xff914890, 0]
proot info: vpid 1: sysexit start: prctl(0x0, 0x2, 0xff9148b0, 0x0, 0x0, 0xf21a34bc) = 0x0 [0xff914890, 0]
proot info: vpid 1: sysexit end: prctl(0x0, 0x2, 0xff9148b0, 0x0, 0x0, 0xf21a34bc) = 0x0 [0xff914890, 0]
proot info: ptrace acceleration (seccomp mode 2, old syscall order) enabled
proot info: vpid 1: sysenter start: execve(0xf1dc82b0, 0xff916a0c, 0xff916a14, 0x2f, 0xf1da2030, 0xff916a0c) = 0xf1dc82b0 [0xff9148a0, 0]
proot info: vpid 1: translate("/" + "/support/extractFilesystem.sh")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/support/extractFilesystem.sh"
proot info: vpid 1: translate("/" + "/support/busybox")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/support/busybox"
proot info: vpid 1: translate("/" + "/support/busybox")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/support/busybox"
proot info: loader: /data/data/tech.ula/files/2/support/prooted-24166-RoW4Bk
proot info: vpid 1: translate("/" + "/support/extractFilesystem.sh")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/support/extractFilesystem.sh"
proot info: vpid 1: sysenter end: execve(0xff914825, 0xff91485e, 0xff916a14, 0x2f, 0xf1da2030, 0xff916a0c) = 0xff914825 [0xff914825, 0]
proot info: vpid 1: sysexit start: restart_syscall(0x0, 0x0, 0x0, 0x0, 0x0, 0x0) = 0x0 [0xffc0aa90, 0]
proot info: vpid 1: sysexit end: restart_syscall(0xffc0a9f0, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xffc0a9f0 [0xffc0a9f0, 0]
proot info: vpid 1: sysenter start: open(0xffc0aa60, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xffc0aa60 [0xffc0a9c8, 0]
proot info: vpid 1: translate("/" + "/support/busybox")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/support/busybox"
proot info: vpid 1: sysenter end: open(0xffc0a99c, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xffc0a99c [0xffc0a9c8, 0]
proot info: vpid 1: sysenter start: uname(0xffc0a7a0, 0x1, 0x10000, 0x0, 0xffc0aa94, 0x8b2a9) = 0xffc0a7a0 [0xffc0a75c, 0]
proot info: vpid 1: sysenter end: uname(0xffc0a7a0, 0x1, 0x10000, 0x0, 0xffc0aa94, 0x8b2a9) = 0xffc0a7a0 [0xffc0a75c, 0]
proot info: vpid 1: sysexit start: uname(0x0, 0x1, 0x10000, 0x0, 0xffc0aa94, 0x8b2a9) = 0x0 [0xffc0a75c, 0]
proot info: vpid 1: sysexit end: uname(0x0, 0x1, 0x10000, 0x0, 0xffc0aa94, 0x8b2a9) = 0x0 [0xffc0a75c, 0]
proot info: vpid 1: sysenter start: brk(0x0, 0x4, 0x0, 0x4c, 0x0, 0x137a44) = 0x0 [0xffc0a8dc, 0]
proot info: vpid 1: sysenter end: mmap2(0x13b000, 0x1000, 0x3, 0x22, 0xffffffff, 0x0) = 0x13b000 [0xffc0a8dc, 0]
proot info: vpid 1: sysexit start: mmap2(0x13b000, 0x1000, 0x3, 0x22, 0xffffffff, 0x0) = 0x13b000 [0xffc0a8dc, 0]
proot info: vpid 1: sysexit end: brk(0x13c000, 0x4, 0x0, 0x4c, 0x0, 0x137a44) = 0x13c000 [0xffc0a8dc, 0]
proot info: vpid 1: sysenter start: brk(0x13cd24, 0x4, 0x13cd24, 0x0, 0x13c000, 0x137a44) = 0x13cd24 [0xffc0a8dc, 0]
proot info: vpid 1: sysenter end: mremap(0x13b000, 0x1000, 0x1d24, 0x0, 0x0, 0x137a44) = 0x13b000 [0xffc0a8dc, 0]
proot info: vpid 1: sysexit start: mremap(0x13b000, 0x1000, 0x1d24, 0x0, 0x0, 0x137a44) = 0x13b000 [0xffc0a8dc, 0]
proot info: vpid 1: sysexit end: brk(0x13cd24, 0x4, 0x13cd24, 0x0, 0x13c000, 0x137a44) = 0x13cd24 [0xffc0a8dc, 0]
proot info: vpid 1: sysenter start: readlink(0x1182f4, 0xffc098d8, 0x1000, 0x1, 0x13a1d0, 0x3) = 0x1182f4 [0xffc098d0, 0]
proot info: vpid 1: translate("/" + "/proc/self/exe")
proot info: vpid 1:          -> "/proc/24167/exe"
proot info: vpid 1: sysenter end: readlink(0xffc098c0, 0xffc098d8, 0x1000, 0x1, 0x13a1d0, 0x3) = 0xffc098c0 [0xffc098c0, 0]
proot info: vpid 1: sysexit start: readlink(0x38, 0xffc098d8, 0x1000, 0x1, 0x13a1d0, 0x3) = 0x38 [0xffc098c0, 0]
proot info: vpid 1: sysexit end: readlink(0x10, 0xffc098d8, 0x1000, 0x1, 0x13a1d0, 0x3) = 0x10 [0xffc098d0, 0]
proot info: vpid 1: sysenter start: brk(0x15dd24, 0x1000, 0x15dd24, 0x0, 0x13cd24, 0x137a44) = 0x15dd24 [0xffc097b4, 0]
proot info: vpid 1: sysenter end: mremap(0x13b000, 0x1d24, 0x22d24, 0x0, 0x0, 0x137a44) = 0x13b000 [0xffc097b4, 0]
proot info: vpid 1: sysexit start: mremap(0x13b000, 0x1d24, 0x22d24, 0x0, 0x0, 0x137a44) = 0x13b000 [0xffc097b4, 0]
proot info: vpid 1: sysexit end: brk(0x15dd24, 0x1000, 0x15dd24, 0x0, 0x13cd24, 0x137a44) = 0x15dd24 [0xffc097b4, 0]
proot info: vpid 1: sysenter start: brk(0x15e000, 0x15dd28, 0x15e000, 0x0, 0x15dd24, 0x137a44) = 0x15e000 [0xffc097b4, 0]
proot info: vpid 1: sysenter end: mremap(0x13b000, 0x22d24, 0x23000, 0x0, 0x0, 0x137a44) = 0x13b000 [0xffc097b4, 0]
proot info: vpid 1: sysexit start: mremap(0x13b000, 0x22d24, 0x23000, 0x0, 0x0, 0x137a44) = 0x13b000 [0xffc097b4, 0]
proot info: vpid 1: sysexit end: brk(0x15e000, 0x15dd28, 0x15e000, 0x0, 0x15dd24, 0x137a44) = 0x15e000 [0xffc097b4, 0]
proot info: vpid 1: sysenter start: access(0x117ea8, 0x0, 0x0, 0x0, 0x37b0d6, 0x0) = 0x117ea8 [0xffc0a82c, 0]
proot info: vpid 1: translate("/" + "/etc/ld.so.nohwcap")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/etc/ld.so.nohwcap"
proot info: vpid 1: translate("/" + "/")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2"
proot info: vpid 1: sysenter end: access(0xffc0a7fe, 0x0, 0x0, 0x0, 0x37b0d6, 0x0) = 0xffc0a7fe [0xffc0a7fe, 0]
proot info: vpid 1: sysexit start: access(0xfffffffe, 0x0, 0x0, 0x0, 0x37b0d6, 0x0) = 0xfffffffe [0xffc0a7fe, 0]
proot info: vpid 1: sysexit end: access(0xfffffffe, 0x0, 0x0, 0x0, 0x37b0d6, 0x0) = 0xfffffffe [0xffc0a82c, 0]
proot info: vpid 1: sysenter start: getuid32(0xffc0b73d, 0x2f2f2f2f, 0x34, 0x6db58a00, 0x139db8, 0xffc0aa94) = 0xffc0b73d [0xffc0a78c, 0]
proot info: vpid 1: sysenter end: getuid32(0xffc0b73d, 0x2f2f2f2f, 0x34, 0x6db58a00, 0x139db8, 0xffc0aa94) = 0xffc0b73d [0xffc0a78c, 0]
proot info: vpid 1: sysexit start: getuid32(0x27c0, 0x2f2f2f2f, 0x34, 0x6db58a00, 0x139db8, 0xffc0aa94) = 0x27c0 [0xffc0a78c, 0]
proot info: vpid 1: sysexit end: getuid32(0x0, 0x2f2f2f2f, 0x34, 0x6db58a00, 0x139db8, 0xffc0aa94) = 0x0 [0xffc0a78c, 0]
proot info: vpid 1: sysenter start: stat64(0xffc0be39, 0xffc0a638, 0xffc0a638, 0x2f, 0x13d958, 0x13dd50) = 0xffc0be39 [0xffc0a604, 0]
proot info: vpid 1: translate("/" + "/data/data/tech.ula/files/2")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2"
proot info: vpid 1: sysenter end: stat64(0xffc0a5e8, 0xffc0a638, 0xffc0a638, 0x2f, 0x13d958, 0x13dd50) = 0xffc0a5e8 [0xffc0a5e8, 0]
proot info: vpid 1: sysexit start: stat64(0x0, 0xffc0a638, 0xffc0a638, 0x2f, 0x13d958, 0x13dd50) = 0x0 [0xffc0a5e8, 0]
proot info: vpid 1: sysexit end: stat64(0x0, 0xffc0a638, 0xffc0a638, 0x2f, 0x13d958, 0x13dd50) = 0x0 [0xffc0a604, 0]
proot info: vpid 1: sysenter start: stat64(0xfb794, 0xffc0a6a0, 0xffc0a6a0, 0x2f, 0x13d958, 0x13dd50) = 0xfb794 [0xffc0a604, 0]
proot info: vpid 1: translate("/data/data/tech.ula/files/2" + ".")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/."
proot info: vpid 1: sysenter end: stat64(0xffc0a5e6, 0xffc0a6a0, 0xffc0a6a0, 0x2f, 0x13d958, 0x13dd50) = 0xffc0a5e6 [0xffc0a5e6, 0]
proot info: vpid 1: sysexit start: stat64(0x0, 0xffc0a6a0, 0xffc0a6a0, 0x2f, 0x13d958, 0x13dd50) = 0x0 [0xffc0a5e6, 0]
proot info: vpid 1: sysexit end: stat64(0x0, 0xffc0a6a0, 0xffc0a6a0, 0x2f, 0x13d958, 0x13dd50) = 0x0 [0xffc0a604, 0]
proot info: vpid 1: sysenter start: open(0xffc0b748, 0x20000, 0x0, 0x0, 0x0, 0x13dd50) = 0xffc0b748 [0xffc0a5d0, 0]
proot info: vpid 1: translate("/" + "/support/extractFilesystem.sh")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/support/extractFilesystem.sh"
proot info: vpid 1: sysenter end: open(0xffc0a597, 0x20000, 0x0, 0x0, 0x0, 0x13dd50) = 0xffc0a597 [0xffc0a5d0, 0]
proot info: vpid 1: sysenter start: wait4(0xffffffff, 0xffc0a0ac, 0x1, 0x0, 0x5, 0x134f8c) = 0xffffffff [0xffc0a088, 0]
proot info: vpid 1: sysenter end: wait4(0xffffffff, 0xffc0a0ac, 0x1, 0x0, 0x5, 0x134f8c) = 0xffffffff [0xffc0a088, 0]
proot info: vpid 1: sysexit start: wait4(0xfffffff6, 0xffc0a0ac, 0x1, 0x0, 0x5, 0x134f8c) = 0xfffffff6 [0xffc0a088, 0]
proot info: vpid 1: sysexit end: wait4(0xfffffff6, 0xffc0a0ac, 0x1, 0x0, 0x5, 0x134f8c) = 0xfffffff6 [0xffc0a088, 0]
proot info: vpid 1: sysenter start: stat64(0x13e6f4, 0xffc09d28, 0xffc09d28, 0x13e730, 0x5, 0x13e8e8) = 0x13e6f4 [0xffc09d1c, 0]
proot info: vpid 1: translate("/" + "/support/rootfs.tar.gz")
proot info: vpid 1:          -> "/data/data/tech.ula/files/2/support/rootfs.tar.gz"
proot info: vpid 1: sysenter end: stat64(0xffc09cea, 0xffc09d28, 0xffc09d28, 0x13e730, 0x5, 0x13e8e8) = 0xffc09cea [0xffc09cea, 0]
proot info: vpid 1: sysexit start: stat64(0x0, 0xffc09d28, 0xffc09d28, 0x13e730, 0x5, 0x13e8e8) = 0x0 [0xffc09cea, 0]
proot info: vpid 1: sysexit end: stat64(0x0, 0xffc09d28, 0xffc09d28, 0x13e730, 0x5, 0x13e8e8) = 0x0 [0xffc09d1c, 0]
proot info: vpid 2: pid 24168
proot info: vpid 1: sysenter start: wait4(0xffffffff, 0xffc0a26c, 0x0, 0x0, 0x13e6d0, 0x134f8c) = 0xffffffff [0xffc0a248, 0]
proot info: vpid 1: sysenter end: wait4(0xffffffff, 0xffc0a26c, 0x0, 0x0, 0x13e6d0, 0x134f8c) = 0xffffffff [0xffc0a248, 0]
proot info: vpid 2: sysenter start: execve(0x13dc14, 0x13dc94, 0x13dcb4, 0x13dcb4, 0x13dc94, 0x13dcb4) = 0x13dc14 [0xffc0a2ac, 0]
proot info: vpid 2: translate("/" + "/support/busybox")
proot info: vpid 2:          -> "/data/data/tech.ula/files/2/support/busybox"
proot info: vpid 2: translate("/" + "/support/busybox")
proot info: vpid 2:          -> "/data/data/tech.ula/files/2/support/busybox"
proot info: vpid 2: sysenter end: execve(0xffc0a273, 0x13dc94, 0x13dcb4, 0x13dcb4, 0x13dc94, 0x13dcb4) = 0xffc0a273 [0xffc0a273, 0]
proot info: vpid 2: sysexit start: restart_syscall(0x0, 0x0, 0x0, 0x0, 0x0, 0x0) = 0x0 [0xffd88c10, 0]
proot info: vpid 2: sysexit end: restart_syscall(0xffd88b8c, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xffd88b8c [0xffd88b8c, 0]
proot info: vpid 2: sysenter start: open(0xffd88bfc, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xffd88bfc [0xffd88b64, 0]
proot info: vpid 2: translate("/" + "/support/busybox")
proot info: vpid 2:          -> "/data/data/tech.ula/files/2/support/busybox"
proot info: vpid 2: sysenter end: open(0xffd88b38, 0x0, 0x0, 0x0, 0x0, 0x0) = 0xffd88b38 [0xffd88b64, 0]
proot info: vpid 2: sysenter start: uname(0xffd88920, 0x1, 0x10000, 0x0, 0xffd88c14, 0x8b2a9) = 0xffd88920 [0xffd888dc, 0]
proot i

**Comment by AdamMatthewLTM** [comment] 2018-11-08 19:20
@AboodiGamer ,

Thank you for including a proot debug log. Can you please also include your device information and any further information you think is relevant such as the steps taken to reproduce this issue?

**Comment by AboodiGamer** [comment] 2018-11-09 23:15
My device is Samsung Galaxy J4.
My Android version is 8.0 Oreo.
After downloading the assets and wasting my time the error happens.

**Comment by EnderNightLord-ChromeBook** [comment] 2018-12-07 06:49
Have you tried this again? Because a new update might fix this (Latest 1.0.3)

**Comment by corbinlc** [comment] 2019-06-20 17:09
No reply in a really long time, so we are closing this.

**Closed by corbinlc** 2019-06-20 17:09 UTC
Labels: bug, invalid, proot

**Comment by TechDossier** [comment] 2019-08-22 02:09
#1003 
Userland is an deadly project 

I am tried more times but get same error.

#1014 #1014 #1013 #867
