### ISSUE TITLE
Feature Request - Snap packages support

### ISSUE THREAD

**Issue by GeorgeKitsopoulos** [CypherpunkArmory/UserLAnd#908] opened 2019-06-19 22:59 UTC
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the problem your feature request solves.
A clear and concise description of what the problem is. 

I am not sure if I should report this as a bug or a feature request but I guess I will give it a shot. On every distro available through the app I cannot use snap apps. I would appreciate if they were available to install. The snaps package gets installed but when I try to install Spotify for example I get this error "sudo snap install spotify
error: cannot communicate with server: Post http://localhost/v2/snaps/spotify: dial unix /run/snapd.socket: connect: no such file or directory"

# Describe the solution you'd like 

If possible I would like the availability of snap or even flatpak packages in order to be able to use certain apps that otherwise may not be available.

# Describe alternatives you've considered

N/A

Please add any other context or screenshots you think might help us resolve your issue.

N/A

**Comment by corbinlc** [comment] 2019-06-20 01:36
I have just created a high level issue to discuss all the things that we cannot do unless we support running as a real root user, #910.
I am closing this one, but please follow #910 for updates, as I have added it to the list found there.  This is to avoid having too many open issues that all have the same root cause.
After we support running a real root user, the device owner will still have to root their device and give us permissions to run as real root.

**Closed by corbinlc** 2019-06-20 01:36 UTC
