### ISSUE TITLE
Feature Request - [SDcard Support]

### ISSUE THREAD

**Issue by MyOctagon** [CypherpunkArmory/UserLAnd#772] opened 2019-04-17 12:53 UTC
# Describe the problem your feature request solves.
A clear and concise description of what the problem is that the app donot allow me to keep the setup files in my external Sdcard.
I don't have much storage in my internal storage so I can not use this app.

# Describe the solution you'd like 
A clear and concise description of what you want to happen. Just add external storage support

# Describe alternatives you've considered
You can also add Some distro which are <100mb like Slitaz Linux.

Please add any other context or screenshots you think might help us resolve your issue.

**Comment by corbinlc** [comment] 2019-04-17 18:50
We have a long standing request to put the files on the SD card, #160 .  Since this is a duplicate of that, I am closing this.  I discuss some of the difficulties of making it run off of the sdcard in that issue.  We have not given up on this idea, but it is a difficult one to solve.

**Closed by corbinlc** 2019-04-17 18:50 UTC
Labels: more-info-required
