### ISSUE TITLE
Bug report - Phone went crazy after uninstalling UserLAnd

### ISSUE THREAD

**Issue by Maingron** [CypherpunkArmory/UserLAnd#684] opened 2019-03-10 17:09 UTC
# Describe the bug
Well, I wanted to uninstall the UserLAnd app and my phone went crazy.

I wanted to uninstall UserLAnd (or rather just delete the app data) and suddenly my phone went crazy. Many apps suddenly threw an "app stopped working" and when I restarted my phone, I didn't want to boot. Fiddled around a bit and got it to boot again. Haven't checked many apps yet, but at least my Youtube app got reset. Also something feels off a bit, can't tell what though. Now I've "successfully" reinstalled the App using the Playstore, but all I get now is a gray screen with sometimes a black flicker in the UserLAnd app. -> Can't use the app anymore for some reason. 

App used about 5GB of internal storage, I have 4GB ram.

# Steps to reproduce the behavior:

1. Install UserLAnd
2. Use it for a while and mess around
3. Go to Settings -> Delete App Data -> wait a few moments

# Screenshots

Wasn't able to screenshot anything. Not sure, what the message was, I got, but it was something with low storage or memory, though I have had over 20 GB free (from 64)

# Device Information

Device: Motorola G6 plus
Android Version: 8.0
UserLAnd Version 2.3.8
Pretty much vanilla Android, if you want so

# Additional context
Feel free to contact me again for additional informations, maybe even using Twitter or something (@maingron)

Inside UserLAnd I firstly installed Firefox, removed it again and then installed Debian and stuff inside Debian.

# Personal analysis: 
Firstly I thought my phone just ran out of RAM, but like I mentioned before, it didn't want to boot then.

**Comment by Maingron** [comment] 2019-03-10 17:18
![image](https://user-images.githubusercontent.com/47825439/54088681-d4f10f00-4360-11e9-9e4c-30e3fe3533ea.png)
grayscreen.png

**Comment by JasonsDoomGitHub** [comment] 2019-03-11 00:34
I had a Similar issue but somewhat different on my Samsung Galaxy j7 sm_j727r4 v.8.1.0 
But instead the app was actually mounting Ubuntu rootfs onto the host-rootfs itself. Now I have about 6 to 7 GB of used storage when it should really be around 2gb 
I also had the grey screen but it went away after I cleared app data and rebooted phone. But I still have around 3gb of used system memory and about 7gb of used internal storage which really doesn't make sense due to the fact that I literally just bought the phone yesterday. My guess is the bug is affecting users that have OS v7.0 and up because I also use Userland on a marshmallow and everything seems perfectly fine

**Comment by Maingron** [comment] 2019-03-11 06:50
https://maingron.de/cloud/index.php/s/EACb4ZefEidf3Ti
Installing and failing at grey screen.mp4
Also sometimes it just crashes.

**Comment by stackerlon** [comment] 2019-03-11 13:12
It might be because in android app data is stored inside /data/data/<package name> or /storage/emulated/0/Android/data/<package name>
And Userland stores the filesystem under /data/data/<package name> and it might be possible that the /data partition is full, I am not 100 percent sure because I do not know much about android partition sizes. And to save get some free space on /data partition system might had reset some of apps.

**Comment by SunbossRS** [comment] 2019-03-11 15:02
Eh there is a mount path in UserLAnd-configured-system ....   
The /storage/emulated/0 in UserLAnd-configured-system is in /mnt/sdcard .....  
So your phone data might hurt....

**Comment by corbinlc** [comment] 2019-03-11 15:09
The only way for that data to get effected is if you run a command that requests it to be deleted or modified.

**Comment by corbinlc** [comment] 2019-03-11 15:16
Android controls all aspects of how apps get installed or uninstalled.  Similar for when you clear data or force stop an app.  I have no idea why it would effect your ability to reinstall this app, boot or run another app.  Android is also responsible for managing how much RAM and disk space we can use, so it should not allow you to get to a place where you have an unusable system.  I and our team have installed an uninstalled or cleared data, so so many times.  We have never seen this and so I don't think we will be able to reproduce this.

**Comment by Maingron** [comment] 2019-03-11 16:05
Also: Do you know a possibility to delete that folder (if it really exists)? Maybe using adb shell?

**Comment by MatthewTighe** [comment] 2019-03-11 16:28
The directory would likely be protected, so you wouldn't be able to delete it without rooting your phone.

**Comment by SunbossRS** [comment] 2019-04-04 11:17
@MatthewTighe   
Each linux system has a SELinux.  
And if you type `rm /*` ,the output will be `cannot remove xxx`.   
But in fact,some folders and files **are hurt**!!  
*(I have been try it in a linux machine*

**Comment by corbinlc** [comment] 2019-06-20 17:17
We have had no other reports of this and have never been able to replicate it.  As such, I am going to close this.  If we ever get more info, we can reopen it.

**Closed by corbinlc** 2019-06-20 17:17 UTC
