### ISSUE TITLE
How to view and kill running processes?

### ISSUE THREAD

**Issue by tokyoneon** [CypherpunkArmory/UserLAnd#512] opened 2019-01-11 02:38 UTC
Hey guys, I'm trying to kill a running service, but many processes are omitted from the `ps` command:

	$ sudo ps auxfwww

	USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
	root      8789  0.0  0.0      0     0 ?        S     2018   0:00 ../support/busybox sh -c ../support/execInProot.sh /bin/bash -c /support/startSSHServer.sh
	root      8791  0.0  0.0      0     0 ?        S     2018   0:00  \_ /data/data/tech.ula/files/support/busybox sh ../support/execInProot.sh /bin/bash -c /support/startSSHServer.sh
	root      8805  0.1  0.0      0     0 ?        R     2018   1:17      \_ /data/user/0/tech.ula/files/support/proot -r /data/user/0/tech.ula/files/8 -v -1 -p -H -0 -l -L -b /sys -b /dev -b /proc -b /data -b /mnt -b /proc/mounts:/etc/mtab -b /:/host-rootfs -b /data/user/0/tech.ula/files/8/support/:/support -b /data/user/0/tech.ula/files/8/support/nosudo:/usr/local/bin/sudo -b /data/user/0/tech.ula/files/8/support/userland_profile.sh:/etc/profile.d/userland_profile.sh -b /data/user/0/tech.ula/files/8/support/ld.so.preload:/etc/ld.so.preload -b /storage/emulated/0:/sdcard -b /data/user/0/tech.ula/files/8/tmp:/dev/shm -b /data/user/0/tech.ula/files/support/stat8:/proc/stat -b /data/user/0/tech.ula/files/support/uptime:/proc/uptime -b /data/user/0/tech.ula/files/support/version:/proc/version /bin/bash -c /support/startSSHServer.sh
	root      8808  0.0  0.0      0     0 ?        Ss    2018   0:00 dropbear -E -p 2022
	root      8818  0.0  0.0      0     0 ?        Ss    2018   0:01  \_ dropbear -E -p 2022
	root      8819  0.0  0.0      0     0 pts/0    Ss    2018   0:00      \_ -bash
	root      8832  0.0  0.0      0     0 pts/0    S     2018   0:00          \_ su
	root      8833  0.0  0.0      0     0 pts/0    S     2018   0:00              \_ bash
	root     13441  0.0  0.0      0     0 pts/0    t+    2018   0:00                  \_ ps auxfwww

For example, `gpg-agent` is running:

	$ gpg-agent --daemon 

	gpg-agent: a gpg-agent is already running - not starting a new one

But it doesn't show up in `ps`. The below command returns no output:

	sudo ps auxfwww | grep -i [g]pg

I'm using the provided UserLAnd Ubuntu distro, fully up-to-date (dist-upgrade), with an Android Nexus phone:

	$ lsb_release -a

	Distributor ID:	Ubuntu
	Description:	Ubuntu 18.04.1 LTS
	Release:	18.04
	Codename:	bionic

I can't get the pid to kill the service and `pkill` doesn't seem to work when using the service/application name.  Is it possible to find and kill processes?

**Comment by MatthewTighe** [comment] 2019-01-23 22:12
@corbinlc Do you have any insight into this?

**Comment by corbinlc** [comment] 2019-02-01 22:09
I think this is a duplicate of #173 .  Please see the conversation there.

**Closed by corbinlc** 2019-02-01 22:09 UTC
