### ISSUE TITLE
Fstat problem when i run ruby

### ISSUE THREAD

**Issue by vingud** [CypherpunkArmory/UserLAnd#392] opened 2018-11-14 15:56 UTC
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory - fstat(2)
Thats the error message when i execute a ruby program.

**Comment by AdamMatthewLTM** [comment] 2018-11-16 19:35
@vingud ,

Thank you for your post. There are known issues with fstat I have run into in the past, but so I can better attempt to narrow down what's causing the issue in your particular case can you please provide me with the following:

The actual ruby program you are attempting to execute (include the source code here), and the device and software information you are working with according to the issue template?

Thank you,
-Adam

**Comment by Herzogs** [comment] 2018-12-07 22:37
hi corbinlc, my problem happens before I want to make a local repository of gems, i want update the repo of gems

My .gemrc

>gemhome: /home/h3rz/.gems
>gempath:
>- /home/h3rz/.gems
>- /usr/lib/ruby/gems/2.3.0

my .bash_profile

>export GEM_HOME=/home/h3rz/.gems
>export GEM_PATH=$GEM_HOME:/usr/lib/ruby/gems/2.3.0
>export PATH=$GEM_HOME:$PATH

And then when i use `gem update` give fstat problem

My Smartphone is Noblex Go2 with Android 5.0 and UserLAnd ver 1.0.3, os Debian 9.0
I'm going to test in ArchLinux and I'll tell you the results

**Comment by corbinlc** [comment] 2018-12-08 00:01
I am not a ruby user, so please back further up and provide the steps from the beginning...like what packages do I need to install?

**Comment by corbinlc** [comment] 2018-12-10 18:40
Thanks for all of the details.  I will work to confirm this issue.

**Comment by corbinlc** [comment] 2018-12-28 19:15
I can now confirm this issue.  I am pretty sure it has to do with how the /proc/$pid/fid/$fidnum is not readable by other processes on some newer versions of Android.  It will require a proot change to fix this.  Can you guys tell me what devices you are using?

**Comment by Herzogs** [comment] 2018-12-28 21:01
I'm use a tablet Acer Iconia one 7 b1-770 with Android 5.0.1 and my smartphone is Noblex Go2 with Android 5.0

**Comment by vingud** [comment] 2018-12-29 17:16
i was using a lg k10 with android 7.1

**Comment by corbinlc** [comment] 2018-12-29 19:04
Oh, those are older versions of Android.  I was definitely wrong about the cause.  Still pretty sure it is proot, but not the reason I expected

**Comment by chris-redekop** [comment] 2019-01-09 22:32
I just found this issue after hitting the same problem.  I observe this same issue on a Samsung Galaxy S9 running Android 8.0.  I can recreate without steps 3-5 above:

1. sudo apt update && apt upgrade
1. sudo apt install ruby
1. gem update (or sudo gem update)

```
ERROR: While executing gem ... (Errno::ENOENT)
No such file or directory - fstat(2)
```

**Comment by amohar** [comment] 2019-02-08 15:45
Hello there,

I have ZTE Blade A530 with Android 8.1 and am having this same issue. both gem update and gem install commands always give me the same error as @chris-redekop. Thanks to anyone trying to help out fixing this issue.

**Comment by corbinlc** [comment] 2019-02-15 21:45
This is fixed for new filesystems.  It involved a major PRoot change that is not compatible with the version being used previously.  We are going to create a path for migrating through major PRoot changes in the not so distant future.  But, the issue with fstat is now fixed.

**Closed by corbinlc** 2019-02-15 21:45 UTC
Labels: proot
