### ISSUE TITLE
Help - [YOUR ISSUE HERE]

### ISSUE THREAD

**Issue by Silithas** [CypherpunkArmory/UserLAnd#727] opened 2019-03-27 01:32 UTC
I followed the tutorial up until this point. After ubuntu supposedly was done, i switched to userland, and was about to do this:

-> In UserLAnd Type: export DISPLAY=:0 PULSE_SERVER=tcp:127.0.0.1:<PORT NUMBER>

But there's nowhere to input that code. Or does it mean to input that in XSDL?

**Comment by foodmaher** [comment] 2019-03-27 09:04
@Silithas 
Follow the code displayed in the XSDL when running and use the internal IP that writes so 127.0.0.1:Port with the word port port b your port is also displayed in the XSDL and will work with you.
**Note:** You must run XSDL before doing anything and also make sure to execute the commands as such and then return to the XSDL and if there is a desktop you installed and if not working with you, run it manually: 

`export DISPLAY=:0`
`export PULSE_SERVER=tcp:127.0.0.1: Port` **Port = A variable**

**Comment by Silithas** [comment] 2019-03-27 20:26
So i can keep port empty? Also, i goofed by using Bvnc app and running userland through it instead of through SSH.

And what port does lxde use? can i just set "1" as the port? or which does it use?

**Comment by lewisdonofrio** [comment] 2019-03-28 19:53
I do startxfce but that is just me ;)

**Comment by lewisdonofrio** [comment] 2019-03-29 00:52
so wait I tried to get xeyes to come though my ssh -Y into the note8 from my desktop running VcXsrv Server and my note8 ip is 192.168.27.148 the desktop is 202 so I tried xhost + on 202 then ssh -Y into 148 export DISPLAY=192.168.27.202:0.0
xeyes and nothing happens ;(

**Comment by foodmaher** [comment] 2019-04-03 14:34
@Silithas 
 **IF** you intend to display desktop via SDL using the [XSDL](https://play.google.com/store/apps/details?id=x.org.server) application, follow the commands that I've written for you.
**OR**
**IF** If you want to view the desktop using the VNC service, you are advised to download the [VNC Viewer](https://play.google.com/store/apps/details?id=com.realvnc.viewer.android) application and load vncserver on your Linux system. And start the server using the `vncserver` command to start the vnc service. 
**AND**
1. Go to the VNC Viewer application after creating the server from your Linux distribution.
2. Create a new connection.
3. Enter the name and port with the ip number like this: **127.0.0.1:port** With the port word being changed to your port
4. Save and start the connection and you will be prompted for the vnc password that you specified earlier.

To disconnect, use the following command `vncserver -kill :port`

Note: You can not extract audio via VNC because it does not support xorg.

**Comment by corbinlc** [comment] 2019-04-12 18:38
This appears to be a duplicate of #729 .  As such, I am closing this.

**Closed by corbinlc** 2019-04-12 18:38 UTC
Labels: more-info-required
