### ISSUE TITLE
Help - [need debian 10 buster]

### ISSUE THREAD

**Issue by qqqwwweee123-arch** [CypherpunkArmory/UserLAnd#986] opened 2019-08-05 07:31 UTC
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the issue you are having.

Hey,
I need to have debian 10 buster on my phone
But the current version of debian 10 buster on UserLand is 10
Please help me to install it through UserLand or other apps
Also my phone Samsung galaxy a9000 is not rooted
Thanks 

# Describe how your task behaves in a regular Linux environment

Describe how the task you are trying to accomplish behaves in a regular Linux environment.

**Comment by FranGamer1892** [comment] 2019-08-06 01:14
try to follow the instructions for debian on the Termux wiki (Termux is a kind of alternative to UserLand) there you should have a way to get a far more updated version of debian

**Comment by MatthewTighe** [comment] 2019-08-08 16:39
Duplicate of #985

**Closed by MatthewTighe** 2019-08-08 16:39 UTC
