### ISSUE TITLE
Bug report - userland directory error '/' 

### ISSUE THREAD

**Issue by TechDossier** [CypherpunkArmory/UserLAnd#1012] opened 2019-08-17 15:18 UTC
#**USERLAND - tar extracting: can't change a directory '/' .Function not implemented**

Hai, 
Am Tech Dossier channel @ YouTube.

Am loving to use your userland in my mobile. But now embracing to report an issue.  Userland has stopped working.  I am tried many time but my data and time was wasted. Please fix this or remove your app in online application stores. 

**Befor**
I am using userland it works awsome bcoz am not rooted my Samsung mobile. I am happy to use that. Really loved. Worlds best no root mobile linux distro app.

**After**
Am hated to use userland in my mobile. Bcoz it was fully bugged and not works good. And not installing any distro now. Am hated and speechless to userland about my channel. Worst technology.
#995 #469 #userland_Error #798 #798

**Comment by corbinlc** [comment] 2019-08-18 06:10
Please see the update on #995 and please try the beta release and tell us how it goes.  I am closing this issue because it is a duplicate of #995.

**Closed by corbinlc** 2019-08-18 06:10 UTC
Labels: more-info-required

**Comment by TechDossier** [comment] 2019-08-18 06:15
> Please see the update on #995 and please try the beta release and tell us how it goes. I am closing this issue because it is a duplicate of #995.

Sure Sir,
I will install and after put here image... Thanks for reply in My mail.
