### ISSUE TITLE
npm throws exception (node.js 10.16.0)

### ISSUE THREAD

**Issue by uu123** [CypherpunkArmory/UserLAnd#938] opened 2019-07-12 10:10 UTC
# Describe the bug
in ssh terminal npm -v throws exception
internal/modules/cjs/loader.js:638
throw err;
^

Error: Cannot find module '../lib/utils/unsupported.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:690:17)
at require (internal/modules/cjs/helpers.js:25:18)
at /usr/bin/npm:19:21
at Object.<anonymous> (/usr/bin/npm:152:3)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

Expected:
6.9.0

# Steps to reproduce the behavior:
1. Create debian filesystem & ssh session
2. start ssh session
3. sudo apt install -y curl
4. sudo curl -sL https://deb.nodesource.com/setup_10.x | sudo bash -
5. sudo apt-get install -y nodejs
6. nodejs -v
output:
v10.16.0
7. npm -v
output:
internal/modules/cjs/loader.js:638
throw err;
^

Error: Cannot find module '../lib/utils/unsupported.js'
at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
at Function.Module._load (internal/modules/cjs/loader.js:562:25)
at Module.require (internal/modules/cjs/loader.js:690:17)
at require (internal/modules/cjs/helpers.js:25:18)
at /usr/bin/npm:19:21
at Object.<anonymous> (/usr/bin/npm:152:3)
at Module._compile (internal/modules/cjs/loader.js:776:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
at Module.load (internal/modules/cjs/loader.js:653:32)
at tryModuleLoad (internal/modules/cjs/loader.js:593:12)

Expected:
6.9.0

# Screenshots
N/A

# Device Information
Device: Galaxy S8
Android Version: P, 9  
UserLAnd Version: 2.5.14-beta-335541 
Whether the device is rooted: NO
Whether the device is running LineageOS: NO

**Comment by uu123** [comment] 2019-07-16 08:30
the same problem with nvm. Should I open separate bug for it?

**Comment by MatthewTighe** [comment] 2019-07-16 16:25
No, we address both in this issue.

**Comment by maxbl4** [comment] 2019-11-16 08:08
Are there any updates on this?
With help of nvm i checked versions of node from 8 to 13. All versions above 8 have this same error in userland debian.
Node 8 works, but it is too old for real usage

**Comment by danielhodder** [comment] 2019-12-27 02:12
The same occurs when using nvm to manage versions of node. As a side-node, which almost looks related, using the arm64 builds of VS-code (https://github.com/headmelted/codebuilds/) also results in a similar load error. It seems like the relative load which was introduced in these later versions of Node isn't working right. Maybe there's a problem in now the working directory is calculated, or maybe there's an error with the loadpath?

**Comment by danielhodder** [comment] 2020-01-02 07:50
I've done some digging and this appears to be the same root cause as libuv/libuv#2282. NodeJS 10.16 added support for the statx system call (nodejs/node#26707). As of that time NodeJS has not been able to work correctly in UserLAnd. It seems like the proot wrapper, or the seccomp filter in UserLAnd is not correctly returning ENOSYS when trying to invoke the statx system call.

**Comment by danielhodder** [comment] 2020-01-02 09:39
Further digging seems to indicate that the cause is proot. The proot binary is swallowing the SIGSYS that seccomp is throwing from trying to invoke this system call. However, looking at the code in https://github.com/termux/proot I'm at a loss to explain that. It seems that if there is a SIGSYS then we should fall through to setting the return value to `-ENOSYS` which should result in the expected code. (https://github.com/termux/proot/blob/master/src/tracee/seccomp.c#L382-L385)

**Comment by rohitranjan1991** [comment] 2020-05-03 13:44
any solution to it yet ??

**Comment by danielhodder** [comment] 2020-05-04 10:05
The issue in proof has been merged so I'm hopeful we'll get a new build once the author has time. They noted they could only work on this in their spare time so hopefully they have time soon.

**Comment by corbinlc** [comment] 2020-05-04 16:28
It is in version 2.7.1.

**Comment by rohitranjan1991** [comment] 2020-05-05 03:10
I can confirm that i am able to install Node js using nvm. Thanks a lot :-)

**Closed** 2020-05-05 03:27 UTC
