### ISSUE TITLE
F-Droid Latest Version.

### ISSUE THREAD

**Issue by rbthomp** [CypherpunkArmory/UserLAnd#751] opened 2019-04-08 23:05 UTC
F-Droid version is not current please update.

**Comment by corbinlc** [comment] 2019-04-09 17:36
Confirmed.  Looks like F-Droid is still at 2.3.8, Play store is at 2.5.3. I will look into it.

**Comment by corbinlc** [comment] 2019-04-09 17:47
It looks like F-Droid is pulling our latest version and the build is succeeding.  Must be something more subtle.  https://f-droid.org/wiki/index.php?title=tech.ula/lastbuild_57&redirect=no

**Comment by corbinlc** [comment] 2019-04-09 18:06
I am seeing what the F-Droid team can tell me, because things looks good.
https://gitlab.com/fdroid/fdroiddata/issues/1592

**Comment by licaon-kter** [comment] 2019-04-09 19:20
Latest version is 2.5.3, use the F-Droid client to get reliable notifications of updates, of course.

Ref. gitlab.com/fdroid/fdroid-website/issues/353

/close this

**Comment by corbinlc** [comment] 2019-04-09 19:48
I had a user report this issue and the website matched their input....of course.

**Comment by corbinlc** [comment] 2019-04-09 19:49
By the website, I mean the f-droid website...of course

**Comment by corbinlc** [comment] 2019-04-09 19:53
@rbthomp, as @licaon-kter points out, the F-Droid repo is up to date, even though the website is not.  I don't know if that is what confused you or not.  I have confirmed this on my device (should have done that first, but I assumed you were correct).  I am seeing 2.5.3 on both the play store and on F-Droid.  If you are not seeing the same you can update your repositories in F-Droid by swiping down.

**Closed by corbinlc** 2019-04-09 19:53 UTC
Labels: more-info-required
