### ISSUE TITLE
Incompatibility with Android <5.0

### ISSUE THREAD

**Issue by sr229** [CypherpunkArmory/UserLAnd#178] opened 2018-08-17 06:15 UTC
App is not compatible to old devices unlike GNURoot. Consider adding backwards compatibility.

Device Information

Device: Huawei Telpad QS
Android Version: Jellybean
UserLAnd Version Latest
Additional context

**Comment by wean-irdeh** [comment] 2018-08-17 10:32
It would be a huge tedious task since Android <5.0 is using Dalvik which has 64k method limitations. Android 5.0 and above does not have such issue.

**Comment by corbinlc** [comment] 2018-08-17 15:14
We originally were going to support 4.0+, but found that our bionic linked executables did not work on versions before 5.0.  I did a little research and found that I needed to use a different NDK version for compiling those to support older versions.  But, 1) I haven't tried that and confirmed it fixes this issue and does not break other things and 2) we have probably started using some APIs that are not supported by older versions of android since we dropped that requirement.  It does not mean it cannot happen, but it makes it more difficult.

**Comment by AdamMatthewLTM** [comment] 2018-09-11 17:59
@sr229 ,

Thanks for your post. I'm going to close this filed issue because of the immense difficulty in supporting android versions older than 5.0 , so if backwards compatibility for those versions is added it will likely be some time in the future. If you feel it is appropriate to keep this thread open, please let me know and I will re-open it.

Thank you for your time and consideration,
-Adam

**Closed by AdamMatthewLTM** 2018-09-11 17:59 UTC
