### ISSUE TITLE
Bug report - debian apt install error

### ISSUE THREAD

**Issue by Zel9278** [CypherpunkArmory/UserLAnd#1079] opened 2019-10-23 22:19 UTC
# Describe the bug
When pcmanfm-qt is installed in debian environment, a dependency error occurs.

# Steps to reproduce the behavior:
N/A

# Screenshots
![Screenshot_20191024-071757_VNC Viewer](https://user-images.githubusercontent.com/43949163/67438449-79913a00-f62e-11e9-8c12-7b894ecdbaf4.jpg)

# Device Information

Device: Galaxy S9+.  
Android Version: 9.0. 
UserLAnd Version 2.6.5.

**Comment by phone-burner** [comment] 2019-10-26 13:59
I met this bug on my Ubuntu devel-branch.
It seems that udisks2 cannot be configured normally with debconf>=2.??(I forgot the version number)on proot env. As a result, enjoying Mate,GNOME,KDE,Cinnamon may be impossible(Xfce is still available乾杯 []~（￣▽￣）~*)
But on my Ubuntu 18.04 LTS,udisks2 works properly. 
The only way to avoid this bug is to use Debian 9 or earlier dists( •̥́ ˍ •̀ू ).

**Comment by corbinlc** [comment] 2019-10-30 19:37
This is a duplicate of the udisks2 issue being discussed here in #1072.  Working on fixing this now.

**Closed by corbinlc** 2019-10-30 19:37 UTC
