### ISSUE TITLE
Error with reading /proc using top, htop and anything else familiar on Android 8.0

### ISSUE THREAD

**Issue by Root-voidX** [CypherpunkArmory/UserLAnd#159] opened 2018-08-06 05:51 UTC
Hello friends!

So to preface the issue. I am running a Samsung Galaxy S9+ SM845 running Android 8.0 on the latest linux kernal.

Using top causes this error:
`top: failed tty set: Permission denied`

Similarly, using htop causes this error:
`Cannot open /proc/stat: Permission denied`

Whatever is causing this is the same reason why certain other apps that require /proc or /data do not work. Hopefully if you guys have any incite on this, please let me know!

**Comment by AdamMatthewLTM** [comment] 2018-08-06 22:01
@Root-voidX ,

Thank you for filing this issue(and thank you -very- much for including your information). This is a duplicate of #87 and #62 , may I recommend closing this one and following those threads? At the moment there isn't an implemented fix, but a workaround exists by installing those utilities separately via toybox. Once an update to those system utilities is provided, it will be updated in those two threads.

Thank you for your consideration,
-Adam

**Comment by corbinlc** [comment] 2018-08-15 04:46
Closing this, please see #173 .  I am going to take a crack at fixing all of these next week and you an track that progress there.

**Closed by corbinlc** 2018-08-15 04:46 UTC
