### ISSUE TITLE
Postgresql-11 error in kali

### ISSUE THREAD

**Issue by Marcus0086** [CypherpunkArmory/UserLAnd#518] opened 2019-01-13 18:57 UTC
Cluster fails on startup script

**Comment by MatthewTighe** [comment] 2019-01-14 17:43
Please update your issue to follow the issue template or your issue will be removed within 3 business days.

**Comment by Marcus0086** [comment] 2019-01-14 17:45
He is saying taht postgresql neither work at startup script nor manually. So waht is really the point of having postgresql installed in the first place.

**Comment by MatthewTighe** [comment] 2019-01-14 17:46
The issue template is provided for a reason. Without reproducible steps and device information, we can't debug your issue.

**Comment by Marcus0086** [comment] 2019-01-14 17:51
Look sir this is not only on my or his device. Just open your app and start kali linux and then create cluster for postgresql. Let's see whether it will end with no error or not. If you don't know hoelw to create cluster then google it 😑😑😑😅

**Comment by Marcus0086** [comment] 2019-01-14 18:10
Hey look my device is MI A1
Android version : 9.0
Postgresql version. 11.1

**Comment by corbinlc** [comment] 2019-01-14 20:44
This is a duplicate of #256.  As such, I am closing this.  As for the template, we are trying to create a behavior pattern where everyone follows it going forward.  Even if you think it doesn't have value, it normally does for us.

**Closed by corbinlc** 2019-01-14 20:44 UTC
