### ISSUE TITLE
Error using VNC to server

### ISSUE THREAD

**Issue by gyme2014** [CypherpunkArmory/UserLAnd#327] opened 2018-10-12 12:51 UTC
Unable to use bvnc to connect to ubuntu or debian: authentication error

authentication error using bvnc

I am using a Lenovo yoga book. I can connect using SSH, but VNC fails. 

to reproduce click Ubuntu or Debian, enter credentials, bvnc starts and you get the error. 

Expected to get a graphical interface
Screenshots

Device Information
Lenovo Yoga Book
Android Version: 7.1.1
UserLAnd Version: .50
Additional context

**Comment by MatthewTighe** [comment] 2018-10-12 15:58
Can you confirm that this has happened on both ubuntu *and* debian? My first guess would be that something was wrong with our vnc password validator. Did you use the same password for both?

**Comment by gyme2014** [comment] 2018-10-12 21:31
It happens on both.

**Comment by corbinlc** [comment] 2018-10-19 21:31
Isn't the Lenovo Yoga Book a Windows device?

**Comment by corbinlc** [comment] 2018-10-19 21:32
Oh, there was an Android version...weird.  The processor is an intel one.  We don't have many users who are non-arm.  I am guessing the issue is in bvnc given that it is saying it is having a connection issue.  Could you try uninstalling bvnc and installing a different vnc client?

**Comment by gyme2014** [comment] 2018-10-20 10:57
You can buy windows or Android.

**Comment by AdamMatthewLTM** [comment] 2018-11-07 16:45
@gyme2014 ,

The VNC client connection issues should have mostly been resolved by this point. I'm going to close this thread, but if they have not been resolved for you with the latest UserLAnd app version, please reply here and I'll re-open this ASAP.

Thanks for your time and patience,
-Adam

**Closed by AdamMatthewLTM** 2018-11-07 16:45 UTC
