### ISSUE TITLE
unable to start userland

### ISSUE THREAD

**Issue by dln949** [CypherpunkArmory/UserLAnd#235] opened 2018-09-04 01:23 UTC
userland 0.3.4 (17)

Samsung Galaxy Tab 2

Android 7.1.2

LineageOS 14.1-20180131-UNOFFICIAL-espressowifi

While loading the assets Userland always hangs on the part about busybox:  
"Extracting: Exec: Failed to execute command [../support/busybox, sh, -c, ../support/execInPro..."

Userland then just hangs, and I have to manually end it.  

The PRoot debug log is attached.  

[PRoot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/2346830/PRoot_Debug_Log.txt)

**Comment by MatthewTighe** [comment] 2018-09-04 16:18
Can you confirm you have the latest update, version 0.3.4?

**Comment by corbinlc** [comment] 2018-09-04 16:54
It looks like the /support/busybox file is there, but something is wrong with it and things die when it is executed.  I wonder if the file is incomplete or otherwise corrupt.  Does uninstalling and reinstalling UserLAnd fix this?

**Comment by dln949** [comment] 2018-09-04 17:04
I do not know how I can "confirm" that I have version 0.3.4 installed - going into the "Help" menu does not show the installed version.  As I wrote in my original post, I have version 0.3.4 installed, but that is based on the version number listed at the URL that I installed UserLand from.  

I uninstalled UserLand and then reinstalled it, still the exact same problem.

**Comment by lukas2005** [comment] 2018-09-21 20:01
Same issue here

**Comment by Zacrain** [comment] 2018-10-11 10:18
I experienced the same problem after installing UserLAnd today on my old Asus TF700T tablet via Google Play. Currently my tablet runs a custom version of Android: Android 7.1.2 katkiss by timduru. The problem occurs when choosing debian. When setting up the filesystem the following error message is displayed:
`Extracting: Exec: Failed to execute command [../support/busybox, sh -c, ../support/execInProot.sh /support/extractFilesystem.sh`.

**Comment by MatthewTighe** [comment] 2018-10-11 16:01
For those that have experienced this issue and not provided a PRoot Debug Log, doing so will help us nail down the cause of this issue.

**Comment by Zacrain** [comment] 2018-10-12 07:01
> For those that have experienced this issue and not provided a PRoot Debug Log, doing so will help us nail down the cause of this issue.

Hope this helps.

[PRoot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/2471936/PRoot_Debug_Log.txt)

**Comment by AdamMatthewLTM** [comment] 2018-11-05 19:36
@Zacrain and @dln949  , 

Sorry this is so late, I'm looking into the issue right now. I know you were asked before to do this, but can you please ensure that you have the latest downloads from the playstore for UserLAnd following these basic steps:

1) Uninstall UserLAnd
2) Clear the phone's cache, and perform basic maintenance clearing out unused files with the android setting app
3) Restart the phone
4) Re-install ULA from the playstore 

Again I apologize for this basic method of trouble-shooting, but while we're looking over the proot logs which you have provided (thank you) I'd like to eliminate any potential unknown variables caused by something obvious like a cache or memory issue.

Thank you for your time and patience in these matters,
-Adam

**Comment by dln949** [comment] 2018-11-06 06:34
After doing what you suggest, Userland works for me now on my device.  

(When I start Userland and the LXDE desktop is starting, I get an error window that says, "No session for PID 30756."  I have NO idea what that is trying to tell me.)

**Comment by AdamMatthewLTM** [comment] 2018-11-07 16:20
To close UserLAnd, you can terminate the app in Android by pressing the window menu button (lower left hand corner) and manually closing all open windows by tapping X in the upper right hand corner, or return to the main ULA session screen and end it from there. I'm going to go ahead and close this thread, if anyone is running into these issues where the reboots I suggested earlier don't work please let me know here.

**Closed by AdamMatthewLTM** 2018-11-07 16:20 UTC
Labels: high priority
