### ISSUE TITLE
Unable to change password

### ISSUE THREAD

**Issue by zaoqi** [CypherpunkArmory/UserLAnd#231] opened 2018-09-01 00:47 UTC
`passwd` can't change password

**Comment by EnderNightLord-ChromeBook** [comment] 2018-09-01 00:54
did you try sudo passwd?

**Comment by AdamMatthewLTM** [comment] 2018-09-05 18:49
This is a duplicate of multiple other issues filed regarding password persistence and changing it. Please file issues according to the template and attempt to see if an issue already exists before making a new one. Thank you,
-Adam

**Closed by AdamMatthewLTM** 2018-09-05 18:49 UTC
