### ISSUE TITLE
su in Ubuntu. incorrect password

### ISSUE THREAD

**Issue by Stainle2S** [CypherpunkArmory/UserLAnd#677] opened 2019-03-06 14:42 UTC
$ su
Password: 
su: Authentication failure

i want up to superuser
i write the my correct password, that i write with start, but he write that pass dont true.
how i can run system with root(su) priv?
sorry for my bad english. im from ukraine. thanx

os: ubuntu
device: blackview a7(rooted)
android: 7.0

**Comment by lewisdonofrio** [comment] 2019-03-07 07:00
"su" works for me - ubuntu 18.04
![screenshot_20190307-015903_userland](https://user-images.githubusercontent.com/3161117/53937953-acc19180-407c-11e9-9657-6c042ce9e321.jpg)
(build guide at http://www.tinyurl.com/donofriodexnote8)

**Comment by corbinlc** [comment] 2019-04-16 19:47
@Stainle2S can you see if `su` works on a new filesystem?  In general, it works fine.  If it works initially, but is broken later on, can you provide all the steps to repeat what you did?  I cannot reproduce this currently.

**Comment by corbinlc** [comment] 2019-06-20 18:36
No feedback provided, as such, I am closing this issue.  Please reopen it after providing more info.

**Closed by corbinlc** 2019-06-20 18:36 UTC
Labels: more-info-required
