### ISSUE TITLE
Recently get this error message every time: Exctracting Tar. Can't change directory to /

### ISSUE THREAD

**Issue by bitcoinmeetups** [CypherpunkArmory/UserLAnd#941] opened 2019-07-13 05:12 UTC
Recently get this error message every time: Exctracting Tar. Can't change directory to /

Cannot install Userland any longer. Android 9. Used to work before. See screenshot. Please advise.

Edit: Additional info. Popup error message says something about files and trying to clear support files.

Clearing cache doesn't work. No idea at the moment.

BM
![Screenshot_20190713-120749_UserLAnd](https://user-images.githubusercontent.com/2834754/61167333-7da9b800-a567-11e9-9d76-123dde2ed5ce.jpg)

**Comment by MatthewTighe** [comment] 2019-07-15 16:50
Had you updated UserLAnd to a new version when this error started appearing?
What version of UserLAnd are you using?
Did this appear on the same device in which you were able to successfully start UserLAnd sessions previously? What device is it?

**Comment by corbinlc** [comment] 2019-09-05 20:07
This is a duplicate of #1014 which was just fixed.  Please update to v2.6.3 once you see that as an option.  This issue should be resolved.

**Closed by corbinlc** 2019-09-05 20:07 UTC
