### ISSUE TITLE
Corrupted data in .git/index (presumably from lstat)

### ISSUE THREAD

**Issue by Unrud** [CypherpunkArmory/UserLAnd#475] opened 2018-12-19 13:11 UTC
When I clone a repo or checkout another branch, I get some corrupted index entries in ``.git/index``.

Example corrupted entry:
```python
 {
  'ctime': 2747408,
  'ctime_nano': 899068,
  'dev': 899176,
  'file_size': 7,
  'flags': 7,
  'gid': 48,
  'ino': 2747408,
  'mode': 33188,
  'mtime': 3900608160,
  'mtime_nano': 899176,
  'path': b'COPYING',
  'sha': b'\x94\xa9\xed\x02M8Yy6\x18\x15.\xa5Y\xa1h\xbb\xcb\xb5\xe2',
  'uid': 2119512
}
```
Correct entry:
```python
 {
  'ctime': 1545178019,
  'ctime_nano': 486999590,
  'dev': 64514,
  'file_size': 35147,
  'flags': 7,
  'gid': 2000,
  'ino': 1322414,
  'mode': 33188,
  'mtime': 1545178019,
  'mtime_nano': 486999590,
  'path': b'COPYING',
  'sha': b'\x94\xa9\xed\x02M8Yy6\x18\x15.\xa5Y\xa1h\xbb\xcb\xb5\xe2',
  'uid': 2000
}
```

**ctime**, **ctime_nano**, **dev**, **gid**, **ino**, **mtime**, **mtime_nano** and **uid** are wrong. The values look random.

To me this looks like the ``stat`` syscall returns corrupted data under some circumstances.

**Comment by corbinlc** [comment] 2019-01-03 02:05
@unrud is this a duplicate of #432 ?

**Comment by Unrud** [comment] 2019-01-03 06:51
> For documenting this issue a little better can you provide how this corruption ultimately results in a error?

After checkout ``git status`` shows changed files, that are not actually changed.
Some functions like ``git rebase`` become unusable, because git detects changes in the workspace while rebasing.

> is this a duplicate of #432 ?

I don't think so.

> Also, can you provide the steps to create that error to make sure I 100% do the same thing?

```
$ git clone https://github.com/CypherpunkArmory/UserLAnd
$ cd UserLAnd
$ git status
```

**Comment by corbinlc** [comment] 2019-01-10 05:30
Thanks for the all the info.  I will try to replicate this issue soon.

**Comment by Unrud** [comment] 2019-04-20 15:29
The problem no longer occurs. I can still reproduce it with an old version of **proot** compiled a few months ago. Maybe the issue was fixes by an NDK update or something.

**Closed** 2019-04-20 15:30 UTC
Labels: proot

**Comment by corbinlc** [comment] 2019-04-20 16:16
Thanks for the update.  I did a lot of PRoot work and squashed several bugs a couple of months back.  Sorry, I didn't test whether this was also fixed.

**Comment by Unrud** [comment] 2019-04-20 17:21
I compiled an old commit of **proot** in the updated built environment and the issue was also gone.
