### ISSUE TITLE
KDE ?

### ISSUE THREAD

**Issue by scott2056** [CypherpunkArmory/UserLAnd#214] opened 2018-08-29 02:04 UTC
Describe the bug

"Could not start D-Bus. Can you call qdbus?" in small window with Okay button when attempting to use KDE desktop via bVNC

Inexperienced user  --  so not sure this is a UserLAnd bug or what the message refers to.

To Reproduce

Install KDE-Standard and use bVNC to attempt to bring up the desktop.

1.  Use Debian file system and ConnectBot
sudo apt-get install KDE-Standard

2.  Use Debian file system and bVNC

Go to '...'
Click on '....'
Scroll down to '....'
See error
Expected behavior

Expected to see KDE Plasma desktop.

Screenshots

Device Information

Device: [e.g. Pixel XL 2] Lenovo Yoga Book
Android Version: [e.g. Oreo, 8.0]  Nougat, 7.1.1
UserLAnd Version [e.g. 0.1.2] 0.2.5
Additional context

**Comment by EnderNightLord-ChromeBook** [comment] 2018-08-29 04:27
Ok you want to install the package: --> plasma <-- to install the kde desktop...

**Comment by scott2056** [comment] 2018-08-30 02:46
Thank you for your comment.  Due to my lack of experience, I'm not sure of your point.  Are you saying that the package "plasma" would not have been installed by installing KDE-Standard?

**Comment by EnderNightLord-ChromeBook** [comment] 2018-09-01 00:44
it installs kde plasma desktop...

**Comment by AdamMatthewLTM** [comment] 2018-09-05 18:30
@scott2056 ,
Thanks for your post and sorry for the late reply. This is a duplicate of issue #157 , in which I stated that we are currently working on implementing fixes for known graphical errors. As soon as I find either a workaround or fix for these known issues, I will update them in the relevant threads users have posted. Since this is a direct duplicate of issue #157 , may I suggest this thread be closed? If you feel it should remain open please reply here with your stated reason and I will go ahead and leave this open.

Thank you for your time and patience in these matters,
-Adam

**Comment by scott2056** [comment] 2018-09-05 21:49
Thank you for your message.  Please proceed with closing the thread as you suggest.

Sent from MailDroid

-----Original Message-----

**Closed** 2018-09-07 15:19 UTC
