### ISSUE TITLE
Downloads don't work

### ISSUE THREAD

**Issue by muchweb** [CypherpunkArmory/UserLAnd#409] opened 2018-11-20 16:14 UTC
Nothing can be installed. Stuck at 'Downloading required assets' screen.

I have left it running for several hours and got this weird screen

![scr](https://user-images.githubusercontent.com/7157049/48786731-22813780-ecf0-11e8-80e6-f1f8bd21e219.jpg)

**Comment by MatthewTighe** [comment] 2018-11-20 17:12
@muchweb Were you able to click the app multiple times before the progress spinner popped up?

**Comment by muchweb** [comment] 2018-11-20 17:48
It says `Downloading required assets…. 0 out of 23 complete`

**Comment by muchweb** [comment] 2018-11-20 18:07
Just noticed that my `/storage/emulated/0/Download` got polluted with hundreds of files (many duplicated). It looks like it was trying to download something…

**Comment by MatthewTighe** [comment] 2018-11-20 18:15
Okay, try clearing those out and trying the downloads again. If you pull down your notification bar you should see the Download Manager downloading the required 23 files. Can you let me know if that successfully completes but UserLAnd still displays that the number is 0 or some other number? If the number UserLAnd displays is larger than 23, that should also be reflected in the Download Manager in the notification tray. That would be an issue as well, but it seems as though the download manager isn't correctly notifying our app when downloads are completed.

Also, which device/Android version/UserLAnd version are you using?

**Comment by muchweb** [comment] 2018-11-20 18:20
Notification says `UserLAnd is running a background service`. It doesn't say anything about the number of downloads.

I'm running Android 8.1.0 (LineageOS 15.1) on star2lte (Galaxy S9+) on network with speed of 90Mbps.

**Comment by muchweb** [comment] 2018-11-20 18:31
No, Download Manager doesn't appear.

Could it be that your app is dependant on Google Play Services™?

**Comment by MatthewTighe** [comment] 2018-11-20 18:36
Nope, we removed all reliance on Google Play Services as we just released to F-Droid. A cursory investigation into LineageOS does make it look like they are using a slightly different version of the `DownloadManager`, but I don't immediately see anything that looks like it would cause this problem.

I don't know enough about the project to know they're build and deployment structure though, so I don't know if this version of the file is the one being used on your device. 

Normally we register a `BroadcastReceiver` that receives broadcasts from the `DownloadManager` whenever downloads are completed, but it looks like your version of Android isn't doing the standard thing. This is gonna be hard to debug without something running that version.

**Comment by corbinlc** [comment] 2018-11-20 18:45
We could install LineageOS on one of our test devices.

**Comment by corbinlc** [comment] 2018-11-20 21:37
Few things.  
1) I have a nexus 7 (2013) running LineageOS 15.1 now.  Downloading and running the app from f-droid is fine.  Except it isn't as clear to the user what client app to get and where to get it from.  bVNC is not on f-droids main repo sadly and the app just says "Please download the associated client app" .  If you are reading this, you can get connect bot from f-droids main repo and bVNC you can get from their github page.
Since it did not fail in the same way for me, this is going to be really hard to reproduce.  Might have to wait for more people to report it and see if it is device specific.

2) Going back to the original report.  It looks like the download manager did in fact get told the downloads completed.  If you look at the screenshot, it shows that more downloads are complete that expected (actually it is 6 times what is expected).  The fact that it is a perfect multiple makes me think somehow the user was able to double click the app and get duplicate downloads.  Our code only check if number download == number expected.  We should not allow multiple app starts to be issued, but assuming that could happen, maybe we should check if the number download >= number expected or something like that.

I am surprised that deleting all the downloaded files and reinstalling the app and staring the process over again would not fix this, as it feels like a corner case.

**Comment by winneratwin** [comment] 2019-02-20 08:42
Stuck at downloading required assets as far as I can see it can only update the package list and its not downloading the files or using any internet for anything else 
On a honor 8 lite 
![screenshot_20190220-093851](https://user-images.githubusercontent.com/32520794/53077931-6ce2a200-34f3-11e9-8372-c254d2e89553.jpg)
![screenshot_20190220-093859](https://user-images.githubusercontent.com/32520794/53077943-73711980-34f3-11e9-9927-049b85206fd9.jpg)

**Comment by corbinlc** [comment] 2019-06-20 17:26
I think that downloading assets works solidly now.  As such, I am closing this issue.  If you see additional issues, please file a new issue with details about that.

**Closed by corbinlc** 2019-06-20 17:26 UTC
