### ISSUE TITLE
Bug report - Synaptic Error

### ISSUE THREAD

**Issue by qqqwwweee123-ping** [CypherpunkArmory/UserLAnd#973] opened 2019-07-28 22:43 UTC
How to use this template:
Any line that begins with '#' is a **header**. Please leave the headers in as is, and fill in the information they suggest
below them. These templates are here to help us resolve your issue as quickly as possible. Leaving requested information out
of your issue will cause our issue template bot to request that your post be reformatted. If a header doesn't seem relevant
to your issue, either write 'N/A' or something similar below the header or consider using a different template.

# Describe the bug

A clear and concise description of what the bug is, and what expected behavior is. Include whether the bug occurs **before** 
or **after** entering a terminal or vnc client session.

# Steps to reproduce the behavior:

A list of **exact** steps to reproduce the behavior. If we cannot follow the steps to recreate the issue, we won't be able
to help you.

For example:

# Screenshots
![62000526-b91db800-b10b-11e9-99b5-2c79da26d04a](https://user-images.githubusercontent.com/53271744/62013889-12e5b700-b1cc-11e9-9f30-c039a30467e9.png)

# Device Information

Device: [Samsung Galaxy A9 (A9000)].  
Android Version: [6.0.1].  
UserLAnd Version [2.6.1].  

Please add any other context you think might help us resolve your issue.

**Comment by MatthewTighe** [comment] 2019-07-29 16:24
This is a duplicate of #916

**Closed by MatthewTighe** 2019-07-29 16:24 UTC
