### ISSUE TITLE
pidof really slow, most of system management tools don't work

### ISSUE THREAD

**Issue by lapsio** [CypherpunkArmory/UserLAnd#62] opened 2018-06-26 08:22 UTC
lapsio@localhost ~> sudo ps -aux
    Error: /proc must be mounted
      To mount /proc at boot you need an /etc/fstab line like:
          proc   /proc   proc    defaults
      In the meantime, run "mount proc /proc -t proc"
    lapsio@localhost ~> sudo top
    top: failed tty set: Permission denied
    
    lapsio@localhost ~> sudo htop
    Cannot open /proc/stat: Permission denied
    lapsio@localhost ~> time pidof pulseaudio
    27881
    0.49user 1.15system 0:09.98elapsed 16%CPU (0avgtext+0avgdata 1124maxresident)k
    0inputs+0outputs (0major+337minor)pagefaults 0swaps

pidof takes many seconds and none of `ps`, `top`, `htop` work. `ss`, `netcat` or `ip`  don't seem to be available at all

**Comment by shcreasey** [comment] 2018-06-26 18:39
I also cannot run top, and firefox runs, but doesn't render  (Samsung galaxy S3)

**Comment by AdamMatthewLTM** [comment] 2018-06-26 20:02
@lapsio ,

Thank you for filing this issue. Please allow me to ask you two questions prior to my recommendation:

1) May I ask which version of Android you are running UserLAnd on?
2) If you have a version of Android running 7.0 by any chance, could you please confirm that these system commands function identically?

There is a chance this issue is directly related to issue #59 , (which is a version specific issue in how system calls are handled) in which case I am recommending these threads be linked together and flagged as high priority/pre production release.

Thank you,
-Adam

**Comment by lapsio** [comment] 2018-06-26 21:56
Android: 8.0.0
Security Patch Level: 5 May 2018
ASUS_Z016D

**Comment by AdamMatthewLTM** [comment] 2018-06-26 22:30
Thanks, I am going to go ahead and mark this thread and issue #59 as duplicates because I have confirmed this is a version issue. This will be marked as high priority. 

Thank you all for your patience in these matters,
-Adam

**Comment by corbinlc** [comment] 2018-06-28 21:46
Since this shows up on 8.0+ but not on older versions of Android, I am going to assume that this has something to do with seccomp filtering and will require another modification into proot.  I will be working on this issue next.

**Comment by corbinlc** [comment] 2018-06-28 23:03
@lapsio for the packages you are saying don't exist, you can install them via apt-get.  Not saying they will work on 8.0+ yet, but only the minimal debian install is put on your system, you have to apt-get anything else.

**Comment by corbinlc** [comment] 2018-08-15 04:45
Closing this, please see #173 .  I am going to take a crack at fixing all of these next week and you an track that progress there.

**Closed by corbinlc** 2018-08-15 04:45 UTC
Labels: SELinux, duplicate, high priority
