### ISSUE TITLE
Bug report - [X Window System error]

### ISSUE THREAD

**Issue by Zel9278** [CypherpunkArmory/UserLAnd#838] opened 2019-05-18 02:10 UTC
# Describe the bug
If I open UserLAnd today, the software has somehow disappeared.

# Steps to reproduce the behavior:
N/A

# Screenshots

![Screenshot_20190518-105931_VNC Viewer](https://user-images.githubusercontent.com/43949163/57963282-04be2380-795d-11e9-8d07-1abed88103eb.jpg)

# Device Information

Device: [galaxy s9+].  
Android Version: [Pie 9.0].  
UserLAnd Version [2.5.9].

**Comment by Nate5700** [comment] 2019-05-18 17:42
I too am having an issue with X in UserLAnd. All of a sudden my desktop environment will not load and I just get a gray screen with a mouse pointer. This is happening on both devices I use it on. What did you guys change?

**Comment by Zel9278** [comment] 2019-05-18 22:38
> I too am having an issue with X in UserLAnd. All of a sudden my desktop environment will not load and I just get a gray screen with a mouse pointer. This is happening on both devices I use it on. What did you guys change?
> 
> I should add that I'm using a Pixel XL running Lineage 16.0 (Pie) and a Pixel 3a XL running Android 9.0 (Pie).

All GTK software stopped working.

**Comment by corbinlc** [comment] 2019-05-19 01:23
We modified PRoot to have basic support for shared memory and semaphores.  I did basic testing of graphical environments before shipping it, but nothing that used GTK.  My guess is that these must be detecting that we now say we support shared memory, but bailing out because we don't support some feature of what they are trying to do.  That is just a guess, but probably a pretty good one, based on what we changed.

Can you guys provide an exact set of commands I can run starting from a new filesystem to reproduce the situation?  That would help a lot.  My test cases all worked.

**Comment by Nate5700** [comment] 2019-05-19 01:40
I was using the MATE environment in Ubuntu. So starting fresh...

sudo apt install mate-core ubuntu-mate-themes
vncserver -geometry 1280x720 :1

Then VNC into the desktop.

**Comment by Zel9278** [comment] 2019-05-19 02:01
First of all, I will make it Japanese.
And "sudo apt install openbox obmenu tint2 wget vim curl mousepad geany gimp terminator openjdk-8-jdk openjfx chromium-browser python-pip python3-pip lxtask gnome-pie pcmanfm-qt lxappearance xarchiver"
I get an error when I try to open "geany"
gimp, terminator, xarchiver, chromium-browser, mousepad, etc. ...
These apps also throw errors.

**Comment by corbinlc** [comment] 2019-05-19 23:49
I will have an update on the cause a progress resolving this by EOD tomorrow.

**Comment by corbinlc** [comment] 2019-05-20 20:14
I have just released a new version of PRoot.  You should see it installing new files the next time you start an app or session (if it is already running you should stop it and restart it to get it to download new files).  

The issues was that the PRoot change added shared memory support, but not perfect support.  Once shared memory was partially supported, programs that could benefit from it started using it.  But, the implementation had a few flaws in it.  All issues seen when recreating the mentioned issues have now been solved.  

Please file new issue for any problem that remains.

**Closed by corbinlc** 2019-05-20 20:14 UTC
Labels: more-info-required
