### ISSUE TITLE
Illegal State - Bad transition at the end of assets download

### ISSUE THREAD

**Issue by lapsio** [CypherpunkArmory/UserLAnd#538] opened 2019-01-18 01:46 UTC
# Describe the bug

Error after assets download

# Steps to reproduce the behavior:

Clear Support Files
start session

# Screenshots

![screenshot_20190118-023546](https://user-images.githubusercontent.com/1054079/51360133-b42bdc00-1aca-11e9-9d4e-a20ea40abc2d.png)

# Device Information

Device: ASUS Zenphone 3 ()
Android Version: Oreo, 8.0
UserLAnd Version 2.2.0
not rooted
stock ROM

# Additional context

Filesystem seems to be functional but I'm not sure if it's serious.

**Comment by MatthewTighe** [comment] 2019-01-18 02:37
Please use the bug report template to update your original post. Reproducible steps, device information, etc is still useful in resolving this issue.

The download process does use Android standard download manager. If you aren't seeing the downloads being down through it, I can only assume you're using a non-standard system.

**Comment by lapsio** [comment] 2019-01-18 03:39
> Please use the bug report template to update your original post. Reproducible steps, device information, etc is still useful in resolving this issue.
> 
> The download process does use Android standard download manager. If you aren't seeing the downloads being down through it, I can only assume you're using a non-standard system.

Updated. I'll post info about download process to thread I previously created on this topi

**Comment by MatthewTighe** [comment] 2019-01-18 18:45
I'm having trouble reproducing this issue. You listed every step necessary to reproduce it on your device?

**Comment by lapsio** [comment] 2019-01-18 19:13
I think It's related to files download problem. There's high chance not all files have been downloaded and launcher proceeded despite not having all necessary assets.

**Comment by MatthewTighe** [comment] 2019-01-18 19:15
Are you unable to reproduce this now? I'd rather leave it open if it's still an issue.

**Comment by lapsio** [comment] 2019-01-18 19:18
Yes, If files are improperly downloaded then there's this error. However I guess as filesystem is old (and fully created already) UserLAnd still manages to launch ssh to it.

**Comment by lapsio** [comment] 2019-01-18 19:19
Also those errors vary. I guess it depends on how many assets have actually been downloaded and how many are missing.

**Comment by MatthewTighe** [comment] 2019-01-18 21:35
@lapsio Are you on the beta channel? I'm thinking of switching to tracking downloads using their ID which should be more robust.

**Comment by MatthewTighe** [comment] 2019-01-18 22:36
Okay, I'm pushing a beta release which might help with downloads a bit. Note that this release will cause crashes after it displays the Illegal State alert. This is so we can gather stack traces from illegal states, and the crash will be removed next week when we move the release to production.

If you continue to have errors, you should be able to remove yourself from the beta program and revert to the current production release. I'll continue to troubleshoot this with you as soon as we are back on Tuesday.

**Comment by Jake-Ackley** [comment] 2019-02-03 07:51
I am having a similar issue on my OnePlus 5 running Android 9, OxygenOS version 9.0.3, UserLAnd version 2.2.1. However, the issue has repeated itself no matter how many times I have uninstalled and reinstalled from both the play store or f-droid. I am not in the beta program and the issue was only present with trying to create a Kali session with Android 8

**Comment by Jake-Ackley** [comment] 2019-02-03 19:32
I believe it is just a remix. I have uninstalled and reinstalled the app countless times, the current version of the app, I have the current updates for my phone as well. I haven't tried different chroots

**Comment by MatthewTighe** [comment] 2019-02-04 17:31
Did you ever close the app while downloads were still in progress? That could cause the issue.

Regardless, I should have a release together today or tomorrow that solves this issue for good.

**Comment by Jake-Ackley** [comment] 2019-02-04 17:32
I've done that once, but it has failed regardless of interaction multiple times

**Closed** 2019-02-07 19:50 UTC
Labels: bug, can't reproduce
