### ISSUE TITLE
Bug report - Firefox 62〜67 not working

### ISSUE THREAD

**Issue by Zel9278** [CypherpunkArmory/UserLAnd#871] opened 2019-06-05 00:43 UTC
# Describe the bug
I noticed that firefox 62-67 does not work

# Steps to reproduce the behavior:
I installed ubuntu, sudo apt update && sudo apt upgrade, and installed the latest version of firefox.

# Screenshots
![Screenshot_20190605-093648_VNC Viewer](https://user-images.githubusercontent.com/43949163/58922515-25b4b000-8776-11e9-83df-d27956d04b05.jpg)

# Device Information

Device: Galaxy s9+.  
Android Version: 9.0 Pie.  
UserLAnd Version 2.5.11.

**Comment by caioprata** [comment] 2019-06-06 22:16
The latest firefox uses hardware acceleration (which is not supported by UserLand)

**Comment by corbinlc** [comment] 2019-06-06 23:09
You could try running firefox with the `-safe-mode` setting

**Comment by corbinlc** [comment] 2019-06-20 17:38
This is a duplicate of #403 , as such I am closing this one.  Please follow and comment on #403.  This has been a long running issue.  We now support shared memory, so we need to investigate what is remaining to support new versions of firefox on ubuntu.

**Closed by corbinlc** 2019-06-20 17:38 UTC
Labels: more-info-required
