### ISSUE TITLE
How do I backup this chrooted install that I've used daily for two months?

### ISSUE THREAD

**Issue by lewisdonofrio** [CypherpunkArmory/UserLAnd#574] opened 2019-01-30 14:31 UTC
Just wondering where does the loopback file exist that ubuntu 18.04 uses in this usermode/userland setup..

**Comment by corbinlc** [comment] 2019-01-30 17:35
Thanks for showing your interest in this feature, we do plan on working on this later, but sadly, we don't have a solution for this yet.  This is a duplicate of #162.  We will track progress on this issue there.

**Closed by corbinlc** 2019-01-30 17:35 UTC

**Comment by MatthewTighe** [comment] 2019-01-30 17:37
If you have a way to access the entire filesystem of your device, your userland filesystem is located at `/data/data/tech.ula/<incrementing id>. You could just manually copy it from there.

**Comment by lewisdonofrio** [comment] 2019-01-30 18:05
Here is what I see, there was a data directory but it has nothing on it , the interal storage I cannot see this "/data/data" directories......

![screenshot_20190130-130322_es file explorer](https://user-images.githubusercontent.com/3161117/52002265-8dd54b80-248f-11e9-971d-c080cd762a63.jpg)

**Comment by lewisdonofrio** [comment] 2019-01-30 18:08
the "local" storage screenshot show's nothing in data
![screenshot_20190130-130306_es file explorer](https://user-images.githubusercontent.com/3161117/52002471-210e8100-2490-11e9-8fd7-a50941bb52cb.jpg)

**Comment by MatthewTighe** [comment] 2019-01-30 18:15
Yeah, I think you'd need to root your device to see the files in an Android file explorer. Each apps' is data is normally hidden for obvious safety reasons. You might be able to extract it using adb though.

**Comment by lewisdonofrio** [comment] 2019-01-30 18:35
can you folks add a ability/function to the userland gui to allow you to make a backup, cause i cannot root my device it's enrolled in enterprise control called "vmware airwatch/intelligent hub." that encrypts the filesystem along with a slew of other policy lockdowns they decide on, so a backup ability before the distro is started within the gui would be best option it seems....

**Comment by MatthewTighe** [comment] 2019-01-30 18:43
As @corbinlc said, this is a planned feature. You can track progress on #162

**Comment by lewisdonofrio** [comment] 2019-02-06 15:38
Build guide and photos at http://www.tinyurl.com/donofriodexnote8 - would be sad if all I can do is rebuild every six months....please add an 'asset' that allows a cp of this chrooted install....

**Comment by MatthewTighe** [comment] 2019-02-06 17:47
Yes, we understand that this is a feature you want. You can track progress on #162. Commenting repeatedly won't make the feature done any faster.

**Comment by lewisdonofrio** [comment] 2019-02-06 17:56
I was not just commenting, I was butting my build guide up in case someone wants to build check it, also was seeing these different assets and it seems like that is how you deal with the chroot installs, so that would be place to go to do that and I'd like to know how I can help this effort - tnx.
