### ISSUE TITLE
Unable to mount proc filesystem.

### ISSUE THREAD

**Issue by madams51703** [CypherpunkArmory/UserLAnd#59] opened 2018-06-21 05:33 UTC
Says it it is write protected and can not mount /proc read only.

**Comment by Root-voidX** [comment] 2018-06-22 18:29
Because you need to be root to mount /proc. Why do you need to mount it anyway?

**Comment by Root-voidX** [comment] 2018-06-23 01:59
I cannot mount all of proc, but maybe go into /host-rootfs/proc and see if you mount whatver files are needed?

**Comment by madams51703** [comment] 2018-06-23 02:40
i will look.  It could be that procps looks to see if /proc is a mount
point.

**Comment by thedward** [comment] 2018-06-24 21:50
If you just want a working `ps`, you can do:

```bash
if ! [ -d $HOME/bin ]
then
  mkdir -pv $HOME/bin
  export PATH=$HOME/bin:$PATH
fi

ln -sv /bin/busybox $HOME/bin/ps
```

Though the BusyBox version isn't terribly featureful — I ended up grabbing `[toybox](http://landley.net/toybox/about.html)`. My architecture is aarch64, so I grabbed `[toybox-aarch64](http://landley.net/toybox/bin/toybox-aarch64)`.

**Comment by AdamMatthewLTM** [comment] 2018-06-26 19:54
@madams51703 ,

Thank you for your reply. May I briefly ask which version of Android you are running UserLAnd on? 

At the moment I am testing this out on Android 7.0 and am able to run ps without any errors. If you are running a different version of Android, it is likely that the handling of this call is different and will result in the requirement to mount Android's /proc as opposed to the UserLAnd proc directory and therefore will cause permissions errors.

If this is the case, I will request that this thread be kept open and marked as high priority/to be fixed before production release.

Thank you for your time,
-Adam

**Comment by AdamMatthewLTM** [comment] 2018-06-26 22:30
Thanks, I am going to go ahead and mark this thread and issue #62 as duplicates because I have confirmed this is a version issue. This will be marked as high priority. 

Thank you all for your patience in these matters,
-Adam

**Comment by madams51703** [comment] 2018-06-27 02:13
Thanks Adam.

**Comment by Root-voidX** [comment] 2018-07-29 16:36
Hey @AdamMatthewLTM any update on this issue? Most of the issues on this github seems to around permission issues with /proc? 

For example my s7e once on Oreo exhihited the same issue as well. Would kernal versions matter to? Because certain work arounds for my exynos 8890/sd820 devices dont work for my sd845 devices

**Comment by AdamMatthewLTM** [comment] 2018-08-14 19:26
@Root-voidX ,

Sorry for the delayed response, I didn't receive an email notification for this one for some reason. At the moment I am unaware of any obvious workaround, except @thedward 's suggestion of using toybox's utility suite. If this is a proot issue it will be worked on and fixed, however I can't provide an exact ETA on that. Can you let me know if the toybox utilities function correctly? I'll try them out myself ASAP. 

Thanks for your patience,
-Adam

**Comment by corbinlc** [comment] 2018-08-15 04:44
Closing this, please see #173 .  I am going to take a crack at fixing all of these next week and you an track that progress there.

**Closed by corbinlc** 2018-08-15 04:44 UTC
Labels: duplicate, high priority, proot

**Comment by ibrado** [comment] 2018-08-22 02:41
@AdamMatthewLTM FYI toybox-aarch64 (Oreo 8.1) ps, top, and netstat all working well. #87

**Comment by Slimking99** [comment] 2023-05-29 16:11
HUAWEI P30 Pro```
10
```
