### ISSUE TITLE
Can't run Raspbian binaries

### ISSUE THREAD

**Issue by tigran123** [CypherpunkArmory/UserLAnd#866] opened 2019-06-04 22:04 UTC
I think I have created this issue before, but can't find it for some reason, so here it is again. The importance of GNURoot Debian is due to the fact that it can run Raspbian binaries and therefore execute one of the most important software packages created on this planet --- Wolfram Mathematica. Now, UserLAnd is supposed to be better and superior and so it should be able to run Raspbian binaries also. But, alas, it cannot:

```
$ file cp
cp: ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, BuildID[sha1]=7527ff4479e970d9bda0929ccd8d2c0a0511b78c, stripped
$ ldd cp
	not a dynamic executable
$ l /lib/ld-linux-aarch64.so.1 
lrwxrwxrwx. 1 tigran tigran 28 Feb  6 21:17 /lib/ld-linux-aarch64.so.1 -> aarch64-linux-gnu/ld-2.24.so
$ l /lib/ld-linux-armhf*
/bin/ls: cannot access '/lib/ld-linux-armhf*': No such file or directory
```

Here is the corresponding session log from GNURood Debian:

```
# ldd /bin/cp
	/support/libdisableselinux.so (0xf7437000)
	libselinux.so.1 => /lib/arm-linux-gnueabihf/libselinux.so.1 (0xf740b000)
	libacl.so.1 => /lib/arm-linux-gnueabihf/libacl.so.1 (0xf73f5000)
	libattr.so.1 => /lib/arm-linux-gnueabihf/libattr.so.1 (0xf73e1000)
	libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0xf72f1000)
	/lib/ld-linux-armhf.so.3 (0x0f000000)
	libpcre.so.3 => /lib/arm-linux-gnueabihf/libpcre.so.3 (0xf7295000)
	libdl.so.2 => /lib/arm-linux-gnueabihf/libdl.so.2 (0xf7281000)
	libpthread.so.0 => /lib/arm-linux-gnueabihf/libpthread.so.0 (0xf725e000)
# l /lib/ld-linux-armhf.so.3 
lrwxrwxrwx. 1 root root 30 Jun 18  2017 /lib/ld-linux-armhf.so.3 -> arm-linux-gnueabihf/ld-2.19.so*
# u
Linux localhost 3.10.84-g21e6a83 #1 SMP PREEMPT Wed Jul 20 15:25:57 KST 2016 armv8l GNU/Linux

```

And this is from LG G4, i.e. the architecture is the same as on the first session (Samsung Galaxy TAB S4).

**Comment by MatthewTighe** [comment] 2019-06-04 22:30
Duplicate of #867

**Closed by MatthewTighe** 2019-06-04 22:30 UTC
Labels: more-info-required
