### ISSUE TITLE
Bug report - [Create new session error]

### ISSUE THREAD

**Issue by SunbossRS** [CypherpunkArmory/UserLAnd#587] opened 2019-02-04 06:06 UTC
(p.s. I am beta via Google-Play)

I have configure a lot of apps before find this bug.

When i create a new app from right top,i choose Debian with vnc.

But i find that app's filesystem is not Debian. It's Kali.

(p.s. Kali is the top one of the "filesystem tab")
---
Now i try to reinstall the UserLAnd and configure other Distributions. I configure Ubuntu,then Kali. But When i create Kali with vnc,the UserLAnd create Ubuntu with vnc.
---

Device: OPPO A57
Android Version: 6.0.1
UserLAnd Version: 2.2.3

![screenshot_2019-02-04-14-01-46-57](https://user-images.githubusercontent.com/38691765/52192560-a675a500-2885-11e9-99de-aada958c5ff5.png)
![screenshot_2019-02-04-14-02-15-94](https://user-images.githubusercontent.com/38691765/52192612-e3419c00-2885-11e9-9cef-3dd7d58ce57e.png)
![screenshot_2019-02-04-14-02-21-10](https://user-images.githubusercontent.com/38691765/52192613-e76db980-2885-11e9-9fe0-b9e5bee2b37a.png)
![img_20190204_140310](https://user-images.githubusercontent.com/38691765/52192617-e9d01380-2885-11e9-9f83-e58c0cb44599.jpg)

**Comment by MatthewTighe** [comment] 2019-02-04 18:14
This is reproducible, but **only if Kali is installed first**. I assume the bug would cause the same thing in the reverse order, or would be true for other distributions. Thanks for bringing this to our attention!

**Comment by foodmaher** [comment] 2019-02-05 08:33
@MatthewTighe 
Is it possible to have the error of the translation file because I think it uses the Chinese language (or similar)

**Comment by SunbossRS** [comment] 2019-02-08 11:01
@foodmaher I used the older versions. The older versions has this problem,too.

**Comment by SunbossRS** [comment] 2019-02-08 11:03
@foodmaher The older version doesn't have Chinese language pack.

**Comment by SunbossRS** [comment] 2019-02-09 03:51
**All right,now i delete the top session of the list. But when i create a session again,it still rephat the fist configure filesystem.**
**Then i delete the top of the "apps". I find the session list of top is change another one.

**Comment by CodeJoule** [comment] 2019-03-17 17:51
I am having the same problem too, except it's correcting my session to use my Ubuntu filesystem instead of Alpine and Arch, which I've tried to reproduce the bug on.

I see #679 was merged, :+1:

**Comment by MatthewTighe** [comment] 2019-03-18 16:17
Yep, expect a release with the fix soon.

**Closed by MatthewTighe** 2019-03-18 16:17 UTC
