### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by Marcus0086** [CypherpunkArmory/UserLAnd#548] opened 2019-01-21 16:16 UTC
Describe the issue you are having.

Pulseaudio not working in kali-lxde.

I'm trying to enable sound in kali-lxde
I've tried enough things like editing client and daemon.conf files and reinstall the whole system.
At first it was saying "could not connect to the Pulseaudio" but now it is stuck at " Establishing connection to Pulseaudio. Please wait."

Describe how your task behaves in a regular Linux environment
In a regular linux environment we have Pulseaudio in working state.

My device: MiA1
Processor: SD625
RAM: 4GB DDR4
Rooted: No
Custom roms(lineageos) : No

Any help will be appreciated

**Comment by MatthewTighe** [comment] 2019-01-23 22:08
What exact steps can we follow to reproduce this issue?

**Comment by Marcus0086** [comment] 2019-01-24 10:54
In order to reproduce the error.
General error:
Open Kali CLI mode and type Pulseaudio there as you can see all the errors.

My error:
Open lxde kali 
Then from lxde start button select sound and then Pulseaudio as you can see " cannot establish connection"

**Comment by MatthewTighe** [comment] 2019-01-24 17:13
Duplicate of #554

**Closed by MatthewTighe** 2019-01-24 17:13 UTC
