### ISSUE TITLE
Mounting a network drive in Linux under UserLAnd

### ISSUE THREAD

**Issue by richardtwyning** [CypherpunkArmory/UserLAnd#1092] opened 2019-11-05 06:46 UTC
Hello, I'm new to UserLAnd and I'm trying to mount a network drive under Linux from the command line.
Here is the command I'm using:
mount -t cifs -o username=richard, password=#####  //192.168.1.7/temp  /host-rootfs/sdcard/Linux/mnt/temp

I've obvious obfuscated my password  ;-)
The response I get is, "Unable to update capability set"

I have installed net-tools, cifs-utils, ping etc.   The server I am trying to mount does ping back successfully.

Any help greatly appreciated.
Many thanks :-)

**Comment by corbinlc** [comment] 2020-01-06 22:11
duplicate of #1093

**Closed by corbinlc** 2020-01-06 22:11 UTC
Labels: more-info-required
