### ISSUE TITLE
Ubuntu on samsung S8  stuck on filesystem installation

### ISSUE THREAD

**Issue by Testato** [CypherpunkArmory/UserLAnd#363] opened 2018-10-27 17:51 UTC
![screenshot_20181027-192803_userland](https://user-images.githubusercontent.com/6893841/47607539-a6ae0b00-da21-11e8-8715-2866b946168f.jpg)

**Comment by AdamMatthewLTM** [comment] 2018-11-08 17:31
This is a duplicate of issue #361 , please see that thread for more additional information.

**Closed by AdamMatthewLTM** 2018-11-08 17:31 UTC

**Comment by JanuszChmiel** [comment] 2018-11-08 17:39
I AM wondering, if this problem which also exist on Samsung Galaxy 5 can 
not be caused by The build in Knox app and I have also found out, that 
Samsung havebuild in detection of low space inside internal storage, so 
system do not allow user to write data if it is 300 MB free, may be that 
they also used swap file or multiple swap file to optimize system 
performance.
I have also found out, that if Samsung Galaxy 5 have 300 MB free or 
less, whole phone board start to produce more and more heat. May be, 
that build in ARM assembli language instructions which are responsible 
for virtual memory creation, swap file can not allocate required swap 
file, so system is being forced to work with RAm very intensively to 
prevent system crash.
