### ISSUE TITLE
Feature Request - Add Live Linux 

### ISSUE THREAD

**Issue by scratchkernel171** [CypherpunkArmory/UserLAnd#884] opened 2019-06-11 12:37 UTC
# Describe the problem your feature request solves.
A clear and concise description of what the problem is. 
Sometimes I feel like Userland uses too much space.

# Describe the solution you'd like 
It would be awesome if the distros could run live, from a squashfs, like regular linux. i.e. space conservation.

# Describe alternatives you've considered
We can have a "export distro to img (for live boot)" feature, so we can boot the squashfs filesystem by mounting the img file (no root if possible for no root users). And wouldn't require to unpack the tar file everytime,

Please add any other context or screenshots you think might help us resolve your issue.

**Comment by luongthomas** [comment] 2019-06-11 16:05
This looks like a duplicate of #885

**Closed by luongthomas** 2019-06-11 16:05 UTC
Labels: more-info-required
