### ISSUE TITLE
Unable to support bluetooth.

### ISSUE THREAD

**Issue by Anonymous1p** [CypherpunkArmory/UserLAnd#263] opened 2018-09-21 16:17 UTC
Can't use BlueBorne
Reason is because it can't access my Android bluetooth.

it can access my Android  sdcard, internet but why not bluetooth.

I think so there should be a bluetooth turn on/off command
so that it can perform bluetooth functions.

if you put effort for this work then it will be a great app.......  really a great app
so plz wakeup your team members and make it possible plz...

Thanks

**Comment by AdamMatthewLTM** [comment] 2018-09-24 18:55
@Anonymous1p ,

Thank you for your suggestion. This is a duplicate of issue #112 and has been labelled as an enhancement/suggestion thread. I will make all updates available on issue #112 regarding when bluetooth will officially be implemented. 

Thank you for your time and consideration,
-Adam

**Closed by AdamMatthewLTM** 2018-09-24 18:55 UTC
