### ISSUE TITLE
Help - Postgresql 11 in kali not work

### ISSUE THREAD

**Issue by reksores** [CypherpunkArmory/UserLAnd#785] opened 2019-04-20 10:12 UTC
# Describe the issue you are having.
Hello,iam using UserLand Kali distro whit s8 . I'm trying to run Postgresql db for metasploit..but  result offline , so I tried to setup it manually...in different ways whit no result whit the same errors

# Describe how your task behaves in a regular Linux environment

azad@localhost:~$ service postgresql start
[warn] No PostgreSQL clusters exist; see "man pg_createcluster" ... (warning).

azad@localhost:~$ pg_createcluster 11 main --start
Creating new PostgreSQL cluster 11/main 
/usr/lib/postgresql/11/bin/initdb -D /var/lib/postgresql/11/main --auth-local peer --auth-host md5
The files belonging to this database system will be owned by user "azad".
This user must also own the server process.

The database cluster will be initialized with locale "C".
The default database encoding has accordingly been set to "SQL_ASCII".
The default text search configuration will be set to "english".

Data page checksums are disabled.

fixing permissions on existing directory /var/lib/postgresql/11/main ... ok
creating subdirectories ... ok
selecting default max_connections ... 20
selecting default shared_buffers ... 400kB
selecting dynamic shared memory implementation ... sysv
creating configuration files ... ok
running bootstrap script ... 2019-04-20 09:53:38.743 UTC [4854] FATAL:  could not create shared memory segment: Function not implemented
2019-04-20 09:53:38.743 UTC [4854] DETAIL:  Failed system call was shmget(key=1, size=56, 03600).
child process exited with exit code 1
initdb: removing contents of data directory "/var/lib/postgresql/11/main"
Error: initdb failed

azad@localhost:~$ psql
psql: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

**Comment by corbinlc** [comment] 2019-04-22 17:10
This is a duplicate of #256.  As such, I am closing it.  Please follow #256 to get updates.  Btw... we are getting closer to a solution than shown in that conversation.

**Closed by corbinlc** 2019-04-22 17:10 UTC
Labels: more-info-required

**Comment by sabri-zaki** [comment] 2019-05-25 10:50
did you solve the problem my friend?

**Comment by sabri-zaki** [comment] 2019-05-25 11:03
@corbinlc I have the same problem and I didn't fond any solution on #256
do you gavé any suggestions
