### ISSUE TITLE
Command ls not working in Kali linux since update to Android 11 on Galaxy A50

### ISSUE THREAD

**Issue by LutzHas** [CypherpunkArmory/UserLAnd#1374] opened 2021-04-08 06:44 UTC
The programs included with the Kali GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Kali GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
user@localhost:~$ ls -lisa
ls: cannot access '.profile': No such file or directory
ls: cannot access '.bash_logout': No such file or directory
ls: cannot access '.bashrc': No such file or directory
ls: cannot access '.bash_history': No such file or directory
total 16
720903 8 drwxrwx--x. 8 10217 10217 4096 Apr  8 05:41 .
656614 8 drwx------. 7 10217 10217 4096 Nov  8  2019 ..
     ? ? -?????????? ? ?     ?        ?            ? .bash_history
     ? ? -?????????? ? ?     ?        ?            ? .bash_logout
     ? ? -?????????? ? ?     ?        ?            ? .bashrc
     ? ? -?????????? ? ?     ?        ?            ? .profile
user@localhost:~$

**Comment by corbinlc** [comment] 2021-04-08 14:48
This happened after doing an `sudo apt upgrade` right?  I have seen this issue.  I don't have a solution yet, but it will probably require a proot change based on what I have seen so far.

**Comment by LutzHas** [comment] 2021-04-08 16:38
sudo apt-get update && sudo apt-get --with-new-pkgs upgrade && sudo apt autoremove

Is my daily update routine that worked for years now.

**Comment by corbinlc** [comment] 2021-04-09 16:31
Ok.  Thanks for confirming.  That is the same issue I am seeing.  Not sure when it will be fixed, but the first step of repeating the problem is done already.  I also already have some logs that I have been looking over for symptoms.

**Closed** 2021-10-03 13:18 UTC
Labels: more-info-required

**Comment by LutzHas** [comment] 2021-10-03 13:19
The probleme is gone since the startx bug was fixed.

**Comment by Tonyoise** [comment] 2025-04-04 03:13
hello am also having the same issue, pls how did u solve it?
thanks
