### ISSUE TITLE
Aapp crashes at downloading required assets

### ISSUE THREAD

**Issue by muggy8** [CypherpunkArmory/UserLAnd#364] opened 2018-10-28 02:14 UTC
Trying to create a new Ubuntu instance on Razer Phone 2 and the app crashes at installing required assets. 

Here's what i did: 
Click on file system tab and then add and create a new file system for Ubuntu
Click on sections tab and create new with the connection type being VNC and targeting the newly created ubuntu filesystem
click on the newly created session and wait 
app crashes

Device Information

Device: Razer Phone 2
Android Version: 8.1.0
UserLAnd Version: 1.0.0

**Comment by AdamMatthewLTM** [comment] 2018-11-08 17:33
This is a duplicate of older posts but it shouldn't be happening right now with that ULA version. I'm going to mark this as high priority and take a look at it ASAP. @muggy8 , please leave this thread open for the time being.

**Comment by java-py-c-cpp-js** [comment] 2018-12-06 14:33
I have the same problem installing firefox or adventure. The app doesn't show how much space it needs and I have only 1.25 GB free space. Maybe the app doesn't notice that there is too less space and crashes because of that?

**Comment by corbinlc** [comment] 2019-09-09 23:12
We have fixed many similar issues over time, so please try again.  This is also really old (our fault for not communicating more).  If this is still an issue, please reopen this.

**Closed by corbinlc** 2019-09-09 23:12 UTC
Labels: high priority
