### ISSUE TITLE
Sporadic host disconnects

### ISSUE THREAD

**Issue by etherealmccoy** [CypherpunkArmory/UserLAnd#91] opened 2018-07-12 11:57 UTC
Userland server disconnects connectbot frequently. Pixel One phone., Oreo.

Most recently has been happening near end of a sudo apt-get install

**Comment by etherealmccoy** [comment] 2018-07-14 04:21
Hi. Answers inline.

On Fri, Jul 13, 2018, 1:26 PM AdamMatthewLTM <notifications@github.com>
wrote:

> @etherealmccoy <https://github.com/etherealmccoy> ,
>
> Thank you for your post. This is an unusual bug which has not come up in
> testing thus far, and may be device-specific - I will mark this as high
> priority for the time being. Please bear with me as I'll ask you some
> questions to better diagnose the problem and attempt to replicate it.
>
>    1. Do you have any power management features implemented on your phone
>    such as battery saver enabled?
>
> None.

>
>    1. Are you simultaneously running any applications alongside userland
>    during the apt installs?
>
> Just the usual. Chrome, GMail. Nothing cpu, io or network intensive.

>
>    1. Has the disconnect occurred more frequently during other specific
>    tasks you are performing?
>
> I haven't been able to figure out a precise pattern, but I have noticed it
a few times toward the end of an apt-get install. Eventually, after a
couple of reconnects, I can complete the install.

>
>    1. Have you successfully been able to install any packages via apt or
>    apt-get before connectbot disconnects?
>
> Yes. Smaller packages generally complete. I think the last time it
disconnected was with jupyter.

>
>    1. If you have a standard *wall* charger available for your device,
>    could you please attempt the same installations while your phone is plugged
>    in and charging? (I am including this last one to rule out things like a
>    defective battery or non-software related power issue).
>
> Will do, and will let you know.

> Thank you for your time and effort in helping to resolve these matters,
>
I really value this software and only wish I had more time to contribute.
Thank you.

**Comment by wyatt8740** [comment] 2018-07-16 07:00
I've had this happen in the middle of large git repository clones before. I am on a Pixel 2 XL running 8.0.

**Comment by AdamMatthewLTM** [comment] 2018-07-18 16:06
@wyatt8740 , 

May I ask what the size of the git repo was, and if there is a public one available on GitHub I may compare against to see if I can trigger the disconnect somehow? 

Both you and @etherealmccoy are using pixel phones, so if this is a hardware issue specific to that model (I am using a samsung) it may not trigger for me, but I will attempt to hunt down that model and see if it is.

**Comment by etherealmccoy** [comment] 2018-07-19 22:21
More data... this just happened several times when the network changed
state (e.g. no LTE connection->LTE connection or the reverse).

**Comment by corbinlc** [comment] 2018-07-20 22:09
Other ssh clients, like JuiceSSH appear to not have this issue, but I can confirm that connectbot does have this issue.  Can you file an issue against connectbot?  As long as other ssh client apps support our ssh URI intent, then our app will work with them.  So, if annoyed by this, until it is fixed, please try a different client app.

**Comment by etherealmccoy** [comment] 2018-07-21 05:15
Thanks. JuiceSSH asks for too many permissions. Termux works great though.
: /

**Comment by wyatt8740** [comment] 2018-07-22 14:41
@AdamMatthewLTM about 500MB.
It has since happened when just idling in a bash shell, as well as while editing files in emacs.

It may be pertinent that I had this trouble in GNUroot as well on my Nexus 6 before this, when using OpenSSH for my SSH daemon.
Dropbear did not exhibit the issue, so I just switched to dropbear on that phone.

**Comment by corbinlc** [comment] 2018-07-23 18:19
We use dropbear for our ssh server currently and most likely going forward.  The server is not terminating though.  It is the client disconnecting.  Are you also using connectbot @wyatt8740 ?  If so, can you look at the conversation above and see if a different client works better?

**Comment by corbinlc** [comment] 2018-07-23 18:20
I am curious what clients work best for people as I we can make our default recommendation different as desired.

**Comment by etherealmccoy** [comment] 2018-09-05 23:12
Still getting this issue on both pixel and samsung tab s, both Termius and ConnectBot. Whenever I will try DropBear. But... from a user pov this feels like a UserLand issue for a few reasons. 
(1) I did not have this issue in GNURoot Debian, which is my "benchmark". 
(2) I could be off-base hers, but.... whenever wan state changes (e.g. 3g->4g, wifi on/off) this happens... why isn't Userland using loopback, impervious to wlan0/eth0 changes?

I get separation of concerns, but this is degrading user experience significantly. Would you consider bundling a default, well-integrated terminal. GNURoot and Termux seem to solve this problem. How?

(To really add a big cherry on top, integrated x-server a la xsdl would be amazing!)

**Comment by corbinlc** [comment] 2018-11-14 15:55
We are going to integrate our own terminal to solve many issues.  We are going to do this right, so it is going to take a bit.  For now, it appears juice-ssh doesn't have this problem, but they are not open source.

**Comment by etherealmccoy** [comment] 2018-11-14 16:51
That is great news. I think it is a good decision. Thank you.

On Nov 14, 2018 10:55 AM, "corbinlc" <notifications@github.com> wrote:

We are going to integrate our own terminal to solve many issues. We are
going to do this right, so it is going to take a bit. For now, it appears
juice-ssh doesn't have this problem, but they are not open source.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CypherpunkArmory/UserLAnd/issues/91#issuecomment-438712740>,
or mute the thread

**Comment by AdamMatthewLTM** [comment] 2018-11-30 10:03
This is technically not solved yet, but because the issue is directly related to the terminal client which is being addressed I am going to close this thread. If new connectivity issues are experienced once the newer clients are launched with UserLAnd, please open a new thread and we'll debug them there.

**Comment by etherealmccoy** [comment] 2018-11-30 12:05
It would make more sense to close it once the new client is released. No?

On Nov 30, 2018 5:03 AM, "AdamMatthewLTM" <notifications@github.com> wrote:

This is technically not solved yet, but because the issue is directly
related to the terminal client which is being addressed I am going to close
this thread. If new connectivity issues are experienced once the newer
clients are launched with UserLAnd, please open a new thread and we'll
debug them there.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/CypherpunkArmory/UserLAnd/issues/91#issuecomment-443153920>,
or mute the thread

**Closed** 2019-03-13 20:56 UTC
Labels: enhancement

**Comment by etherealmccoy** [comment] 2019-03-13 22:42
Hi. Hoping this was closed due to upcoming integrated terminal? Thanks for
the hard work on this.
