### ISSUE TITLE
Feature Request - Add the ability to change install location of filesystem

### ISSUE THREAD

**Issue by slycooper724** [CypherpunkArmory/UserLAnd#714] opened 2019-03-19 19:53 UTC
# Describe the problem your feature request solves.
My phones internal storage is very limited, but I have an external sd card. Therefore I made it so UserLAnd installs to the sd card. Still UserLAnd is using space on my internal storage, an annoying fact since I just exported the app to my extarnal sd card.

# Describe the solution you'd like 
I would like an option to change the storage location of my filesystem in the same prompt that asks me to give a username and password and also from the filesystems tab also.

# Describe alternatives you've considered
N/A

# Additional context
N/A

**Comment by corbinlc** [comment] 2019-04-12 18:54
This is a duplicate of #160.  As such, I am closing this.  This is a pretty difficult issue to solve, but we have done some investigation into it.  Please star #160 if you are interested in following any progress..

**Closed by corbinlc** 2019-04-12 18:54 UTC
