### ISSUE TITLE
Help - [systemctl]

### ISSUE THREAD

**Issue by qian9008** [CypherpunkArmory/UserLAnd#854] opened 2019-05-29 04:40 UTC
systemctl can't use in  chroot

**Comment by qian9008** [comment] 2019-05-29 06:54
In short, the true Linux can not be fully simulated in the chroot or proot environment 。nspawn Maybe better!

**Comment by corbinlc** [comment] 2019-06-20 01:42
I have just created a high level issue to discuss all the things that we cannot do unless we support running as a real root user, #910.
I am closing this one, but please follow #910 for updates, as I have added it to the list found there.  This is to avoid having too many open issues that all have the same root cause.
After we support running a real root user, the device owner will still have to root their device and give us permissions to run as real root.

**Closed by corbinlc** 2019-06-20 01:42 UTC
Labels: more-info-required
