### ISSUE TITLE
Chromebook Support 

### ISSUE THREAD

**Issue by EnderNightLord-ChromeBook** [CypherpunkArmory/UserLAnd#359] opened 2018-10-25 04:26 UTC
are chromebooks supported (armhfp, i3 and AMD64)

**Comment by corbinlc** [comment] 2018-10-30 19:32
I have heard of people using the app on chromebooks.  We have not tested it on them yet, but "should" support the correct architectures.  What are you seeing?

**Comment by EnderNightLord-ChromeBook** [comment] 2018-11-07 05:57
I can't launch apps on VNC mode... but I can successfully get lxde desktop working... I tried using unity but errors came up... gnome I haven't tried...

**Comment by EnderNightLord-ChromeBook** [comment] 2018-11-07 05:59
It should be alright... Chromebook support is a YES for some aspects

**Comment by AdamMatthewLTM** [comment] 2018-11-08 17:09
This is a duplicate of multiple posts for chromebook support, so I'm going to close this thread for now. All future updates for this topic will be posted to the relevant original thread issues. If anyone feels this should remain open for any reason, please tell me your reasoning and I will re-open it ASAP.

Thank you for your time and patience,
-Adam

**Closed by AdamMatthewLTM** 2018-11-08 17:09 UTC
