### ISSUE TITLE
Unable to run top or netstat

### ISSUE THREAD

**Issue by g33k247** [CypherpunkArmory/UserLAnd#87] opened 2018-07-09 22:02 UTC
![screenshot_20180709-180358](https://user-images.githubusercontent.com/8498814/42478423-acac7332-83a2-11e8-9c39-071ed3b94acc.png)

When I try to execute a simple top command, I get "top: failed tty set: Permission denied user" and netstat, "bash: netstat: command not found"

**Comment by AdamMatthewLTM** [comment] 2018-07-11 19:50
@g33k247 , 

Thank you for your post. May I ask if you are using the current latest version of the app and which android version you are using? This is the first time I have seen a permissions issue for a command such as top, so providing as much information as possible is integral to solving this. Thank you for your time,
-Adam

**Comment by corbinlc** [comment] 2018-07-11 19:53
@AdamMatthewLTM I think this is a duplicate of #59 and #62 
This won't occur on your test device since it is Android 7.0 
After I finish fixing the huawei issue, I might send you that device, so you have something running 8.0+

**Comment by g33k247** [comment] 2018-07-11 21:32
Android 8.1.0 and app v0.1.2

**Comment by etherealmccoy** [comment] 2018-07-12 12:31
ps does not work either
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"

**Comment by thedward** [comment] 2018-07-14 16:12
Not a fix, but both the `top` and `ps` provided by [`toybox`](http://landley.net/toybox/)  seem to work as expected. The project s even kind enough to provide a precompiled [aarch64 binary](http://landley.net/toybox/bin/toybox-aarch64).

**Comment by corbinlc** [comment] 2018-08-15 04:44
Closing this, please see #173 .  I am going to take a crack at fixing all of these next week and you an track that progress there.

**Closed** 2018-08-15 04:45 UTC
Labels: duplicate

**Comment by rebroad** [comment] 2021-01-17 15:40
@corbinlc maybe re-open this as it's still an issue as of now on the latest OS on Samsung Galaxy S10
