### ISSUE TITLE
Feature Request - [Run Distros Live]

### ISSUE THREAD

**Issue by scratchkernel171** [CypherpunkArmory/UserLAnd#885] opened 2019-06-11 12:39 UTC
# Describe the problem your feature request solves.
Sometimes I feel like Userland uses too much space.

# Describe the solution you'd like 
It would be awesome if the distros could run live, from a squashfs, like regular linux. i.e. space conservation.

# Describe alternatives you've considered
We can have a "export distro to img (for live boot)" feature, so we can boot the squashfs filesystem by mounting the img file (no root if possible for no root users). And wouldn't require to unpack the tar file everytime,

**Comment by corbinlc** [comment] 2019-06-20 01:38
I have just created a high level issue to discuss all the things that we cannot do unless we support running as a real root user, #910.
I am closing this one, but please follow #910 for updates, as I have added it to the list found there.  This is to avoid having too many open issues that all have the same root cause.
After we support running a real root user, the device owner will still have to root their device and give us permissions to run as real root.

**Closed by corbinlc** 2019-06-20 01:38 UTC
