### ISSUE TITLE
Bug report - ["chmod 700 /sys" doesn't work on kali]

### ISSUE THREAD

**Issue by n0di** [CypherpunkArmory/UserLAnd#605] opened 2019-02-09 17:48 UTC
Good day. I apologize for my bad English. I have a redmi s2 device with a 3.18.71-perf-g6a82bd7 kernel. I think that I installed all the necessary packages for correct work, but I cannot get " chmod 700  /sys ". please help with this problem. I also have some problems with the "top" command
Thanks in advance for your help!

**Comment by MatthewTighe** [comment] 2019-02-11 19:25
You'd need to use `sudo chmod 700` to change the permissions of a directory immediately under root, such as `/sys`. Note doing so may have unintended consequences.

**Comment by n0di** [comment] 2019-02-11 20:48
Dear developers! I tried all the options for chmod. I tried both from the root and from the regular user. I would not write if the problem was only in sudo. nothing works for /sys.
thanks for the answer

**Comment by n0di** [comment] 2019-02-11 20:50
> You'd need to use `sudo chmod 700` to change the permissions of a directory immediately under root, such as `/sys`. Note doing so may have unintended consequences.

Dear developers! I tried all the options for chmod. I tried both from the root and from the regular user. I would not write if the problem was only in sudo. nothing works for /sys.
thanks for the answer

**Comment by corbinlc** [comment] 2019-02-11 20:51
I can confirm that you cannot `chmod` that directory.  Can you tell me a little about why people are asking to change the permissions of that directory?  It may help me not only fix `chmod /sys` but also confirm it solves your ultimate goals.

**Comment by n0di** [comment] 2019-02-11 20:57
> Я могу подтвердить, что вы не можете `chmod`этот каталог. Не могли бы вы рассказать мне немного о том, почему люди просят изменить разрешения для этого каталога? Это может помочь мне не только исправить, `chmod /sys`но и подтвердить, что оно решает ваши конечные цели.


started giving an error _init_ at the beginning. I did not pay attention to it, since I worked through ssh. then I decided to check aircrack-ng, but due to the fact that I do not have the necessary level of access to the /sys folder, the aircrack-ng package did not work for me

**Comment by corbinlc** [comment] 2019-02-11 20:58
Can you tell me the exact commands you tried for `aircrack-ng` so I can try them and reproduce the errors it encounters?  I have never used that tool, so some pointers would be appreciated.

**Comment by n0di** [comment] 2019-02-11 21:16
![photo_2019-02-12_07-16-30](https://user-images.githubusercontent.com/44620146/52594016-27d8c300-2e96-11e9-94ee-810637151fc3.jpg)

**Comment by n0di** [comment] 2019-02-11 21:22
> Can you tell me the exact commands you tried for `aircrack-ng` so I can try them and reproduce the errors it encounters? I have never used that tool, so some pointers would be appreciated.

![photo_2019-02-12_07-16-30](https://user-images.githubusercontent.com/44620146/52594304-e72d7980-2e96-11e9-8a9d-84c1e4c44958.jpg)

**Comment by n0di** [comment] 2019-02-11 21:31
вот еще некоторые проблемы с которыми я столкнулся

![photo_2019-02-12_07-30-10](https://user-images.githubusercontent.com/44620146/52594825-33c58480-2e98-11e9-969e-c4c1837aa479.jpg)

![photo_2019-02-12_07-30-14](https://user-images.githubusercontent.com/44620146/52594836-388a3880-2e98-11e9-9c57-baa313d18213.jpg)

**Comment by n0di** [comment] 2019-02-11 21:33
I apologize for earlier if I did something wrong or did not understand. since i am not a professional user)))

**Comment by casept** [comment] 2019-02-15 17:15
@n0di,
Your issues make me think that you don't quite understand how UserLand works.
Basically, a root user is emulated without actually having root privilege over the android system. This means that you can do stuff as root inside UserLand (like installing packages), but anything that requires "real root" on Android (like raw access to device files) will not work.

This means that you can't run aircrack from within UserLand, no matter how you try to `chmod` (because you have no permission to do it on `/sys`, a directory managed by Android).

If you want to have "real" root which allows for this, consider rooting your phone and using the `Linux Deploy` app.

As for your NetworkManager issue, that's once again related to how UserLand isn't really an independent Linux system. All the networking is managed by Android, which means there's nothing NetworkManager can do, and that's why it's not running.

**Comment by corbinlc** [comment] 2019-09-09 23:33
#910 would have to be taken care of if you were to want to actually be able to `chmod` that directory.  Closing this since #910 is open and has more info.

**Closed by corbinlc** 2019-09-09 23:33 UTC
