### ISSUE TITLE
Phone went crazy after uninstalling the app

### ISSUE THREAD

**Issue by Maingron** [CypherpunkArmory/UserLAnd#683] opened 2019-03-10 16:38 UTC
Hi! I discovered UserLAnd yesterday and have experimented quite a bit since then. Now I wanted to make actual use of UserLAnd, so I decided to reinstall the app. The moment I clicked on Clear App Data, many random apps throw a "app stopped working" and I wasn't really able to open an app anymore. I then decided to restart my phone and it got stuck. Just the typical Bootscreen of my phone. Eventually I fiddled around a bit and it booted again. Then I uninstalled the app using the Playstore - worked fine. Also: Haven't really looked at many apps yet, but I got kicked out of my YouTube app, used it a few minutes before. So I wanted to reinstall the app but I only get a gray screen now, sometimes a quick black flicker. 
Motorola G6plus, Android 8, no root

**Comment by MatthewTighe** [comment] 2019-03-11 16:19
What version of UserLAnd are you using?

**Comment by MatthewTighe** [comment] 2019-03-11 16:22
Duplicate of #684

**Closed by MatthewTighe** 2019-03-11 16:22 UTC
Labels: more-info-required
