### ISSUE TITLE
Re-open my session after closing UserLand 

### ISSUE THREAD

**Issue by Guioman** [CypherpunkArmory/UserLAnd#637] opened 2019-02-16 00:51 UTC
Each time I close the app even when nothing is installing or setting up, I can't re-open my session. I can watch it when I go to the session tab, I can kill it and re-open the ssh debian session, I enter my password and the black window of the terminal appears and suddenly closes. When I click back on my session, it's the same thing, the terminal window appears and closes. I tried to create a new ssh ubuntu session, the same thing happens. I uninstalled and reinstall UserLand, always the same thing. It's very boring to wait for update, upgrade and install some tools Iike python or R and finally not to be able to use those tools if I close UserLand or if it closes itself...

**Comment by corbinlc** [comment] 2019-02-16 00:52
Please update based on the template, but based on your Play Store review, it looks like you are using an Huawei device running Android 8.0.  We are having several issues with Huawei devices running 8.0 specifically.  Are you able to update to EMUI 9?  If so, the problem will probably go away.

**Comment by Guioman** [comment] 2019-02-16 01:02
Yes indeed I am using an Huawei device running Android 8.0. Not sure I can update it, I will try. Thanks a lot for your quick and accurate answer.

**Comment by corbinlc** [comment] 2019-04-16 19:43
Have you been able to upgrade to EMUI 9?  Did this fix your issue?

Regardless, this is a duplicate of #398 and we will track Huawei Android 9 issue here #398

**Closed by corbinlc** 2019-04-16 19:43 UTC
Labels: more-info-required
