### ISSUE TITLE
Stuck on "Starting Service..."

### ISSUE THREAD

**Issue by biom4st3r** [CypherpunkArmory/UserLAnd#71] opened 2018-06-29 11:44 UTC
I created a filesystem, made a session, and downloaded the required assets. When I tap the session I made it just stays on starting service... and creates the background service notification.

On verbose 9 the debug log only says "checking 1". I have tried wiping data and reinstalling to no effect. Attempting to connect via bvnc while its on starting service gives a connection refused(ECONNREFUSED). 

I am using a " LeEco le pro3" android version 8.1.0

**Comment by biom4st3r** [comment] 2018-06-29 13:39
I've also left it running since the initial report to make sure it was given enough time to fully load and there is no change

**Comment by Pixead** [comment] 2018-06-29 20:53
Same problem... using a honor p9 lite under android 8.0

**Comment by AdamMatthewLTM** [comment] 2018-06-29 21:47
@biom4st3r , 

Thank you for posting this issue. This sounds very similar to one I personally ran into (issue #47 near the end). Before I apply any flags to this post, could you please take a look at the steps listed in that thread and confirm if the theoretical fix works and the behavior is similar to your issue?

Thank you so much,
-Adam

**Comment by AdamMatthewLTM** [comment] 2018-06-29 21:58
@Pixead , 

My apologies - the 'honor p9 lite' mobile device is in fact a Huawei device. While my recommendation to @biom4st3r was pointed to the correct thread, I am also going to recommend that for your device specifically you please take a look at issue #48 which has been flagged as high priority.

If you feel this is an inappropriate link to that particular thread, please reply here with reasons why.

Thank you so much for your time and patience everyone,
-Adam

**Comment by biom4st3r** [comment] 2018-06-30 10:34
@AdamMatthewLTM,

Sorry but i don't have the resources to download android studio. I'm currently sharing 1mbps between 15-18 people. It took 3 days for me to get the Debian image

**Comment by AdamMatthewLTM** [comment] 2018-07-02 14:41
@biom4st3r ,

My apologies. At the moment I do not have a current workaround to this particular issue that does not involve compilation with Android Studio. For the time being, I will be marking this as high priorty and as a duplicate of thread #47 . When a workaround is implemented this and thread #47 will be immediately updated.

**Comment by AdamMatthewLTM** [comment] 2018-08-14 19:32
I am closing this thread because this issue should have been fixed. Please create a new issue if a similar problem is experienced, thank you.

**Closed by AdamMatthewLTM** 2018-08-14 19:32 UTC
Labels: bug, duplicate, high priority
