### ISSUE TITLE
Synaptic

### ISSUE THREAD

**Issue by GuyFromMars365** [CypherpunkArmory/UserLAnd#69] opened 2018-06-28 17:01 UTC
I can't get the Synaptic Package Manage GUI to pull up in LXDE. How should I troubleshoot? Also, I did notice during installation mention about a tcsaflush or TCSA not being uninstalled because access denied? Related?

**Comment by sstt011** [comment] 2018-07-01 04:12
@GuyFromMars365 Did you get LXDE working? Did you have the problem from #20?

**Comment by GuyFromMars365** [comment] 2018-07-01 17:16
I'm getting LXDE up, but no Synaptic Gui, as of now. If this helps, below is a dialogue I get when I SSH to start LXDE:
user@localhost:~$ startlxde             
** Message: main.vala:102: Session is LXDE                                      
** Message: main.vala:103: DE is LXDE   
                                        
(lxsession:26789): Gtk-WARNING **: cannot open display: :0                      
user@localhost:~$

**Comment by nakele** [comment] 2018-07-03 08:52
First make sure you check this: https://github.com/CypherpunkArmory/UserLAnd/issues/45

Then once you have lxde running and opened in XServer Android app, you need to open the Root terminal application from within lxde and launch synaptic from there.

**Comment by GuyFromMars365** [comment] 2018-07-06 03:30
How do I do that? And why won't it launch within LXDE via GUI?  Also, many other things do not launch as well. I also cant get the on-screen keyboard to appear, but not sure if that us related to XSDL app.

**Comment by nakele** [comment] 2018-07-06 13:01
Try this:
1. Open XServer XSDL Android app and make sure you get to the blue screen.
2. From the userland console copy and paste this(all in the same same line): DISPLAY=127.0.0.1:0 PULSE_SERVER=t
p:127.0.0.1:4712 startlxde &
3. Go back to XServer app and wait for few seconds
4. Once lxde has started go to system tools>Root terminal
5. Type synaptic

Synaptic should start.

Ps. You need to install synaptic via atp-get install and the XServer from the Android PlayStore

**Comment by GuyFromMars365** [comment] 2018-07-06 14:05
No dice. On-screen keyboard never pops up.

**Comment by nakele** [comment] 2018-07-06 14:08
The on screen keyboard should pop up on XServer XDL when you press "back" on your phone. It's not a Debian keyboard, it's the Android one.

**Comment by GuyFromMars365** [comment] 2018-07-06 14:18
Thanks. Worked great. Why wont synaptic & other things launch in gui?

**Comment by nakele** [comment] 2018-07-06 14:20
I don't know, maybe because of the way the root works in this setup? Don't know, need to ask the dev of this app.

**Comment by AdamMatthewLTM** [comment] 2018-09-16 20:11
@GuyFromMars365 and all others in this thread,

Sorry for the delayed response. I'm going to go ahead and close this thread for the time being, if anyone feels it should be re-opened please let me know with your reasoning and I'll go ahead and re-open it.

Thanks everyone,
-Adam

**Closed by AdamMatthewLTM** 2018-09-16 20:11 UTC

**Comment by GuyFromMars365** [comment] 2018-09-16 20:50
@AdamMatthewLTM, is there another thread where this issue is being discussed? @nakale offered a workaround, but one in my instance of debian, opening Synaptic in the Desktop Environment does nothing.

**Comment by GuyFromMars365** [comment] 2018-09-24 03:37
So Synaptic will still not run from Gui, or Libre Office Writer. But, Firefox & Gimp load just fine. :/ Thoughts? Does this shed any light: https://neil-black.co.uk/raspberrypi/install-gui-package-manager-on-the-raspberry-pi/

**Comment by JanuszChmiel** [comment] 2018-09-24 06:37
I will analyse The produced errors. Please always use Xserver XSDL, 
since this X server for Android do its best to support all Xserver 
capability as in standard Linux distributions.
Please keep in mind, that Userland run user space Linux and we have to 
be very patient, since such kind of repair require many many hours from 
experienced C programmers.  Firstly, it is necessary to determine The 
cause of this bug. In some cases, it is problem in GTK library, which is 
responsible for GUI creation, in some cases, it is problem caused by The 
fact, that currently C Linux apps which are using Userland can not 
allocate shared memory, or shared memory file.
It would require experienced C or C++ programmer to redesign apps from 
scratch, or repair hydden issues inside Proot and related .so library. 
It is not always simply possible, since Userland run in conjunction with 
Android Kernel.
By other words, Userland shares CPU resources and other system resources 
with Android kernel and other Android specific modules. There also build 
in ARM CPU limitations, in some cases, very deep Assembly language 
knowledge is required to overcome such kind of bugs.
I hope, that also engaged developers of Userland will confirm some of my 
assumptions which I have write in this post.
For now, it is possible to run mainly apps without desktop environment 
such as Firefox, I will test many other apps including Libre office.

**Comment by GuyFromMars365** [comment] 2018-09-24 13:51
Until this is permanently resolved, I found a fix: 
[https://askubuntu.com/questions/185755/synaptic-package-manager-doesnt-launch-from-the-application-menu](url)

My method:
1) Launch SSH session in Userland
2) Install Nano text editor: apt install nano
3) Open file in nano: sudo nano /usr/share/applications/synaptic.desktop
4) Change line Exec=synaptic-pkexec to Exec=gksudo synaptic
5) Ctrl+ to overwrite and Ctrl+X to exit.
6) Kill SSH session and open up VNC session! :) 

Bear in mind I put the instructions above for those who want to try to use userland, but are new to linux (like me).

**Comment by JanuszChmiel** [comment] 2018-09-24 18:45
I have executed synaptic. And it do not produce error message when I 
have opened SSH session.
May be, that something strange is being drawn on The Xserver XSDL screen 
but I can not analyse this since I do not see. I can try to make screen 
shot from XSDL session and I can try run OCR software to find out, if 
Synaptic produces usable text output on The screen.

**Comment by GuyFromMars365** [comment] 2018-09-24 19:59
Mmmm, I just did the vnc & did not bother with XDLS, as it's too much hassle for me.
