### ISSUE TITLE
Bug report - Failed to extract filesystem

### ISSUE THREAD

**Issue by Zom101** [CypherpunkArmory/UserLAnd#1046] opened 2019-09-10 17:06 UTC
# Describe the bug

The phone received an update to android 9.0 and the app no longer works. It gives an error when extracting the files. It worked fine on android 8.0.

# Steps to reproduce the behavior:

1. Open the app.

2. Select any distro.

3. The app downloads and verifies the files.

4. "UserLAnd has entered an illegal state!" appears.

# Screenshots

![Screenshot_20190910-193630](https://user-images.githubusercontent.com/55152960/64633405-d1b80800-d403-11e9-8d82-e723109d4806.png)
![Screenshot_20190910-194627](https://user-images.githubusercontent.com/55152960/64633406-d2509e80-d403-11e9-8d9e-b83bdd99ace3.png)

# Device Information

Device: Motorola Moto G6 Play.  
Android Version: 9.0.  
UserLAnd Version 2.6.3.  
Whether the device is rooted - no.  
Whether the device is running LineageOS - no.

Log: 
[Proot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/3596845/Proot_Debug_Log.txt)

**Comment by corbinlc** [comment] 2019-09-10 17:14
This is similar but different vs an issue we just fixed on some Samsung devices #1014.  I will need your help trying out some fixes for this as I don't have a device that shows this issue, but we should be able to sort it out.

**Comment by Zom101** [comment] 2019-09-10 17:34
Thank you for the quick response. I am willing to help.

**Comment by corbinlc** [comment] 2019-09-10 21:02
Can you try this out and provide another PRoot log regardless of whether it works or not?
Please uninstall the previous version first.

https://github.com/CypherpunkArmory/UserLAnd/releases/download/proot-chdir/app-debug.apk

Thanks!

**Comment by Zom101** [comment] 2019-09-11 04:56
It goes a little further now, but gives another error.

[Proot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/3599000/Proot_Debug_Log.txt)

**Comment by corbinlc** [comment] 2019-09-11 05:05
Did you have the verbosity set to 9 before running?  I don't see most of the proot messages, but I do see that it got further.  Could you check and repeat the log creation?  Sadly you probably have to uninstall and reinstall to get the same behavior again...or maybe you could install a different distribution after checking the verbosity setting.  Just need to see more of the debug prints like what was in the first log you provided.

**Comment by Zom101** [comment] 2019-09-11 05:55
Sorry, i forgot about the verbosity level.


I uploaded it on google drive because it wos too big: https://drive.google.com/file/d/109ELPa1vsHlDhg1_03O_kwbBXhylce2G/view?usp=drivesdk

**Comment by corbinlc** [comment] 2019-09-11 17:51
@Zom101 same deal. 

Can you try this out and provide another PRoot log regardless of whether it works or not?
Please uninstall the previous version first.

https://github.com/CypherpunkArmory/UserLAnd/releases/download/proot-chdir/app-debug.apk

I only have a hunch on what the issue is this time, so I am not very confident that this will work, but it is worth a shot.  This one is a little odd and there isn't much info to go off of.  If this hunch doesn't work, I will need to see what other debug info I can print that might help.

Thanks!

**Comment by corbinlc** [comment] 2019-09-11 17:56
This apk will not work on arm64 devices, it is just a test for this armhf device issue.  If this works, I will make the change robust for all architectures.  So if anyone else is reading this, please don't use this apk without trying to help debug the issue mentioned above which is specific to armhf devices.

**Comment by Zom101** [comment] 2019-09-11 18:58
Still doesn't work, same things happening.

Log: https://drive.google.com/file/d/109ELPa1vsHlDhg1_03O_kwbBXhylce2G/view?usp=drivesdk

**Comment by Zom101** [comment] 2019-09-11 19:34
I just tried another distro (arch) and it did not give an error, but it hangs at sarting service. The log was huge (over 200mb) and after the starting service message its size dropped to 30kb

[Proot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/3602412/Proot_Debug_Log.txt)

**Comment by LabYab** [comment] 2019-09-11 19:35
Hey, hi sorry for my English I'm still learning the language.
I have the MOTOROLA E5 PLUS and I had the same error the app did not work but with this last apk that you attached advanced a little, all the processes end without error but the screen remains in "Starting service". I attached the log. In case it helps you. Thank you.
[Proot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/3602410/Proot_Debug_Log.txt)

**Comment by fotiskar** [comment] 2019-09-12 01:31
I face the exact same issue on Huawei Mate 10 lite running EMUI 8.0.0

**Comment by corbinlc** [comment] 2019-09-13 16:48
@LabYab I only commented on this issue over on a Termux issue because...
1) I found their solution was not as robust as ours
but mainly...
2) I may have been the first person to use PRoot in an Android app, back on GNURoot, but @michalbednarski is he expert and his help may be required to sort this out.

**Comment by LabYab** [comment] 2019-09-13 17:02
Sure! I understand you, thanks for your dedication. While researching this issue, I am using userland on my S8+ where it works perfectly.
When you make a change if you need proofs or logs let me know. Thank you.

**Comment by michalbednarski** [comment] 2019-09-13 19:32
Okay, I'll need racap on issue on UserLAnd side.
This issue is about void SIGSYS on 32-bit arm or something else? Was there fix attempt that was ineffective?
What's wrong with [my fix](https://github.com/)?

**Comment by MatthewTighe** [comment] 2019-09-13 19:35
@michalbednarski The link you shared just goes to `github.com`

**Comment by corbinlc** [comment] 2019-09-13 19:43
@michalbednarski  I explain what is wrong on the proot issue you worked on...
termux/proot#71

**Comment by corbinlc** [comment] 2019-09-13 19:44
but yes, this is impacting some armhf devices.

**Comment by Zom101** [comment] 2019-09-15 07:40
> Okay, I'll need racap on issue on UserLAnd side.
> This issue is about void SIGSYS on 32-bit arm or something else? Was there fix attempt that was ineffective?
> What's wrong with [my fix](https://github.com/termux/proot/commit/0c2da8185123486e17d0bb1fd3d27cc2152bbcff)?
> 
> Edit: fixed link

I don't know what i'm talking about here, but when using termux (latest version, which should include that fix) the situation looks like this:

![Screenshot_20190915-103054](https://user-images.githubusercontent.com/55152960/64918256-61630b00-d7a4-11e9-9287-cc4251b91be2.png)

And also, just like with userland, it worked before the android pie update.

**Comment by corbinlc** [comment] 2019-09-18 18:14
@Zom101 since you know how to show part of this issue in termux, can you file an issue here: https://github.com/termux/proot/issues
That might get better feedback from @michalbednarski .
After he fixes the result (the thing I did to push this a little further), you will probably start getting the signal 11's in a variety of cases in termux same as in UserLAnd.  I have a feeling this is a problem with ASLR or something like that on armhf devices and I will most likely need help in solving this.

**Comment by corbinlc** [comment] 2019-09-18 18:15
I do see some issues that report signal 11's on armhf devices for termux's proot, but they are not well written issues and that is probably why they have not gotten attention.

**Comment by Zom101** [comment] 2019-09-19 07:35
Ok, i just opened an issue there too. 
https://github.com/termux/proot/issues/75#

**Comment by corbinlc** [comment] 2019-09-19 21:43
@Zom101 and @LabYab  and others,

Can you try this out and provide another PRoot log regardless of whether it works or not?
Please uninstall the previous version first.

https://github.com/CypherpunkArmory/UserLAnd/releases/download/proot-chdir/app-debug.apk

You will notice things run noticeably slower with this version.  Please be patient.  The results will help this issue eventually get fixed in a performant way.

Thanks!

**Comment by LabYab** [comment] 2019-09-19 23:25
Hey, currently it is stopped in the message "Extracting: Output redirecting to proot debug log, but it takes almost more than an hour and a half and does not advance. I sent you the log that created the app.
[Proot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/3633549/Proot_Debug_Log.txt)
![Screenshot_20190919-164941](https://user-images.githubusercontent.com/55209039/65287989-c3a46e80-db0a-11e9-9486-641cf23a8e01.png)
![Screenshot_20190919-181754](https://user-images.githubusercontent.com/55209039/65287990-c69f5f00-db0a-11e9-8f29-beacee4ea5eb.png)

**Comment by LabYab** [comment] 2019-09-19 23:30
Try to close the app and run it again and this appears to me
![Screenshot_20190919-182828](https://user-images.githubusercontent.com/55209039/65288178-87bdd900-db0b-11e9-82e2-586774a428e7.png)

**Comment by Zom101** [comment] 2019-09-20 03:42
It took less than a minute to give me an error, so i can't see any difference in speed, but that's probably beacuse it did not extract the files:

[Proot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/3634118/Proot_Debug_Log.txt)

**Comment by Zom101** [comment] 2019-10-07 19:13
> Ok, i just opened an issue there too.
> [termux/proot#75](https://github.com/termux/proot/issues/75)

Problems fixed.

**Comment by corbinlc** [comment] 2019-10-07 19:14
I have been following.  I should have a merged version of the proot changes included very soon.  Thanks for working on this.

**Comment by corbinlc** [comment] 2019-10-09 21:41
Aliright @Zom101 and @LabYab  and others,

Can you try this out and provide another PRoot log regardless of whether it works or not?
Please uninstall the previous version first.

https://github.com/CypherpunkArmory/UserLAnd/releases/download/proot-chdir/app-debug.apk

This has merged in the work that was done in termux for this same issue.

Thanks!

**Comment by Zom101** [comment] 2019-10-10 06:10
[Proot_Debug_Log.txt](https://github.com/CypherpunkArmory/UserLAnd/files/3710722/Proot_Debug_Log.txt)

**Comment by corbinlc** [comment] 2019-10-10 15:50
Now need to see if this works on the devices that were already fixed in #1014 .  Those devices were also armhf and using a newer version of Android, but they behaved differently.  Need to make sure this change does not break them.  If it does not, then I think we have a winner for moving forward from this problem.

**Comment by corbinlc** [comment] 2019-10-17 05:04
@Zom101 this is now in the latest beta and production releases of UserLAnd.  If you can confirm that everything looks good, we can close this.  Thanks for working with everyone to resolve this issue!

**Closed** 2019-10-17 09:45 UTC
