### ISSUE TITLE
Bug report - [tar: can't change directory to '/': Function not implemented] ver. 2.6.2

### ISSUE THREAD

**Issue by x2slasher** [CypherpunkArmory/UserLAnd#1014] opened 2019-08-21 14:29 UTC
# Describe the bug

When the app downloaded the assets and tried to setting up filesystem I got the message "tar: can't change directory to '/': Function not implemented]".

# Steps to reproduce the behavior:

This issue occurs every time when I try to install Kali or Debian

# Screenshots

![Screenshot_20190820-184723_UserLAnd](https://user-images.githubusercontent.com/54324481/63440496-934cb000-c438-11e9-9139-4f5b50236c90.jpg)

# Device Information

Device: Samsung Galaxy J5  (Not rooted)
Android Version: 8.1.0  
UserLAnd Version: 2.6.2-beta-663767

**Comment by MatthewTighe** [comment] 2019-08-22 03:47
Providing a [PRoot Debug Log](https://github.com/CypherpunkArmory/UserLAnd/wiki/Generating-PRoot-Debug-Logs) would likely be helpful in resolving this issue.

**Comment by x2slasher** [comment] 2019-08-22 19:35
It not creates any debug log. Especially not in mnt/sdcard. 
![Uploading Screenshot_20190822-222023_UserLAnd.jpg…]()
Doing this since 15 minutes after it downloaded the assets for debian

**Comment by x2slasher** [comment] 2019-08-22 19:50
Okay here it is: https://file.io/xoS4jY

**Comment by x2slasher** [comment] 2019-08-22 19:55
Okay here it is: https://www.mediafire.com/file/1w6jevaq5i702j9/Proot_Debug_Log.txt/file

**Comment by corbinlc** [comment] 2019-08-23 07:35
Thanks.  I will be able to work on this Monday.  I don't have a device that shows this issue, but if you are willing to keep trying out solutions, we should be able to get it fixed pretty soon.

**Comment by x2slasher** [comment] 2019-08-23 15:43
All right. I will try to do what I can.

**Comment by x2slasher** [comment] 2019-08-27 09:58
Okay the previous message not appear, but it still stops while extracting and building up file system. It tried to extract the files for like an hour I don't think it's normal to take so long.
https://www.mediafire.com/file/sshllyfuuim6oix/Proot_Debug_Log.txt/file

**Comment by corbinlc** [comment] 2019-08-29 15:38
@x2slasher Just tagging you now, because I forgot to mention you yesterday when I had the new APK ready.  Please see the new APK when you have the chance.  Thanks!

**Comment by x2slasher** [comment] 2019-08-30 09:02
Still not works. here is the log: http://www.mediafire.com/file/96m8ja97f6tln07/Proot_Debug_Log.txt/file
No problem I have enough time for this. :D

**Comment by corbinlc** [comment] 2019-08-30 17:02
Baby steps.  Ugh, the issue is nastier than I thought.  It is not that new system calls are being blocked, it is any system call where we change the sysnum to `PR_void` to skip running the actual system call is being blocked, but in a different way than on other devices.  Normally, it throws an error when `PR_void` is executed.  These devices are letting it actually try to run the bogus system call and then throwing the error afterwards.  This is going to take a few more go around, but now I actually understand how this problem is different than other system call filtering that occurs.

**Comment by corbinlc** [comment] 2019-08-30 17:06
So, I am going to detect whenever the system call is set to `PR_void` and save off what should have been the result and set a flag that I have done so.  Then if it gets blocked during or after the system call, I will check if the flag is set.  If it is, I will set the saved off result as the final result and allow things to continue gracefully.  That _should_ work.

**Comment by corbinlc** [comment] 2019-08-31 00:41
@x2slasher same deal...

New apk to try. It is the same link as before https://github.com/CypherpunkArmory/UserLAnd/releases/download/proot-chdir/app-debug.apk

Please uninstall and they install this apk and tell me how things (mis)behave. A PRoot log would be nice regardless of whether it works or not.

Thanks again!

**Comment by x2slasher** [comment] 2019-09-01 14:42
Well things are moving but still not working. Now it stucked here: https://www.mediafire.com/file/l08y2gsmae0b8bg/Proot_Debug_Log.txt/file
It says "Starting service" for hours.

**Comment by corbinlc** [comment] 2019-09-01 15:33
Ok cool.  I think I know what is needed now.  Hopefully, it only takes one more itteration.  Thanks @x2slasher!  Will get back to you later.

**Comment by corbinlc** [comment] 2019-09-03 05:37
@x2slasher same deal...

New apk to try. It is the same link as before https://github.com/CypherpunkArmory/UserLAnd/releases/download/proot-chdir/app-debug.apk

Please uninstall and they install this apk and tell me how things (mis)behave. A PRoot log would be nice regardless of whether it works or not.

This is the first one that has a shot a solving it, now what I understand the problem fully.

Thanks again!

**Comment by paoloperissin** [comment] 2019-09-03 12:36
Good morning.
I have the same problem and this problem happens after the last android 9 update. Before everything works properly
Thanks

**Comment by x2slasher** [comment] 2019-09-03 17:15
Good news. It works with Kali. With ubuntu I got the same results (endless "Starting service")
BUT (yes it's a huge but) when i try to login it can't accept the password I gave it. 
https://i.imgur.com/p6SSbZb.jpg

**Comment by x2slasher** [comment] 2019-09-03 17:17
Good news. It works with Kali. With ubuntu I got the same results (endless "Starting service")
BUT (yes it's a huge but) when i try to login it can't accept the password I gave it. 
https://i.imgur.com/p6SSbZb.jpg

**Comment by corbinlc** [comment] 2019-09-03 17:23
@x2slasher Can you provide a proot log for both Kali and Ubuntu?

**Comment by corbinlc** [comment] 2019-09-03 17:26
Also, @x2slasher, is it Kali that is having trouble accepting your password?  Can you double check you are originally entered the password you thought (you can long press on a filesystem on the filesystem tab, hit edit and then reveal your password).

**Comment by corbinlc** [comment] 2019-09-03 19:06
@paoloperissin If you want to join the fun, can you 1) tell me what device you have and 2) try the latest apk mentioned above.  Whether it works or not, 3) providing a [PRoot Debug Log](https://github.com/CypherpunkArmory/UserLAnd/wiki/Generating-PRoot-Debug-Logs) would be helpful.

**Comment by x2slasher** [comment] 2019-09-03 20:38
If it's not a problem i need 2 days for the debug log. I changed my net provider and they didn't connected yet and I've already made this test with my limited mobile data. Also yes the Kali and double checked the password.

**Comment by corbinlc** [comment] 2019-09-03 20:58
Unless you have uninstalled the app again, running it to capture the PRoot logs should not consume much data (the large downloads happen on first install).  That being said, a PRoot log itself can sometimes be big and it is your data, so I appreciate the logs whenever you can provide them, even if that means 2 days.

**Comment by paoloperissin** [comment] 2019-09-04 07:34
Good morning.
 I have tried the last apk version. The error is the same, but if I stop and reopen the application the filesystem start. The problem is that don't accept the password.
In attach two files, one with my phone datails and the other one with the PRoot Debug log.

Have a nice day
Bye


https://www.dropbox.com/s/ttz2vdcwo9kvjth/Screenshot_20190904-090607_Settings.jpg?dl=0

https://www.dropbox.com/s/ij4bmyx27c16vja/Proot_Debug_Log.txt?dl=0

**Comment by corbinlc** [comment] 2019-09-04 16:55
Thanks @paoloperissin that is very helpful and the log did help me understand something I am doing wrong.  I will have a new apk soon.  As I mentioned to @x2slasher, I am sorry I have to pull you into the debug, but some issues are device or android version specific and we don't have a device that shows this issue.  I think we are close to solving the issue though.

**Comment by corbinlc** [comment] 2019-09-04 17:34
@paoloperissin same deal...

New apk to try. It is the same link as before https://github.com/CypherpunkArmory/UserLAnd/releases/download/proot-chdir/app-debug.apk

Please **uninstall** and then install this apk and tell me how things (mis)behave. A PRoot log would be nice regardless of whether it works or not.

Thanks again!

**Comment by paoloperissin** [comment] 2019-09-04 17:54
I have tried the new version. The error is the same. 
In attach the log
Have a nice day
Paolo


https://www.dropbox.com/s/ij4bmyx27c16vja/Proot_Debug_Log.txt?dl=0

**Comment by corbinlc** [comment] 2019-09-04 18:05
This log now looks pretty good.  The thing I tried to fix in the last iteration looks better.  I am think the issue is earlier on during extraction.  I need to modify the program to not overwrite the Proot_Debug_Log at every step, so you can easily provide the log for just extraction step.  It is currently getting overwritten when it starts the ssh server.  I will get back to you later today most likely with another attempt.  Thanks @paoloperissin!

**Comment by paoloperissin** [comment] 2019-09-04 18:25
Hi
In attach two log:
- the first one (extraction) is the log of the installing fase
- the second one (startaftererror) is the log produced when I restart application after error that arrive at the prompt login, but doesn't accept any password

https://www.dropbox.com/s/ij4bmyx27c16vja/Proot_Debug_Log_extraction.txt?dl=0

https://www.dropbox.com/s/50w114nifs9e11d/Proot_Debug_Log_startaftererror.txt?dl=0

**Comment by corbinlc** [comment] 2019-09-04 18:43
@paoloperissin The first log looks like it is not complete.  You probably tried to kill it at just the right time to only get the extraction.  This new apk https://github.com/CypherpunkArmory/UserLAnd/releases/download/proot-chdir/app-debug.apk will capture a different Proot log each time PRoot is executed.  Can you uninstall and try the new one?  It will behave the same, but you should end up with 2 logs.  I would like them both.  Thanks again!

**Comment by corbinlc** [comment] 2019-09-04 18:44
Make sure you turn on the PRoot debug logging right away, before setting up a distro.  Thanks!

**Comment by paoloperissin** [comment] 2019-09-04 19:17
I have done the following steps:
- install the app - evrything OK
- start setting up disto - start extract file but never stop (remain blocked extracting /media) after the known error 
- skip back, relanch app, go to the installed distro and tap on it - this time extraction arrive at the end, but when the ssh terminal open, it is impossible to put the password (no one is accected)

Following the log

https://www.dropbox.com/s/r9xh2qoqyyuq6rq/Proot_Debug_Log.txt0?dl=0
https://www.dropbox.com/s/lilsy5cjph9013u/Proot_Debug_Log.txt1?dl=0
https://www.dropbox.com/s/vn61e1s6pbzisbv/Proot_Debug_Log.txt2?dl=0

**Comment by corbinlc** [comment] 2019-09-04 20:10
Oh goodness.  We are getting a SEGV from some part of PRoot that I did not touch.  This might take a bit.  
In general, what is happening is certain system calls are being blocked starting with Android 8.0, but different per version of Android (manufacturers who customize Android have also made some tweaks to which calls are blocked).  Some devices that are armhf and not arm64 are now getting updated to versions of Android that have some system calls blocked, but the way that armhf handles blocked systems calls is different.  I am now handling that difference and restoring the result to what it should be, but something about this is not quite sufficient.  When handling an `execve` call that was turned into a `void` call, because the file did not exist, the result was corrupted and before I could fix it, some part of PRoot used the corrupt result and accessed some part of memory it is not allowed to.  I need to find out where this is occurring and figure out how to detect and avoid this situation.
I don't expect anyone else to understand all that, but this will probably take a few iterations to fix.  Darn, I thought we were really close.

**Comment by paoloperissin** [comment] 2019-09-04 20:27
According to the different time zone (I'm from Italy) I remain available. 
Thanks
Paolo

**Comment by corbinlc** [comment] 2019-09-04 21:14
Ok.  I think I see what is going on.  I will have a new apk very soon that will try to fix this last issue.
Thanks!

**Comment by corbinlc** [comment] 2019-09-04 21:17
@paoloperissin same deal...

New apk to try. It is the same link as before https://github.com/CypherpunkArmory/UserLAnd/releases/download/proot-chdir/app-debug.apk

Please uninstall and then install this apk and tell me how things (mis)behave. The PRoot logs would be nice regardless of whether it works or not.

Thanks again!

**Comment by paoloperissin** [comment] 2019-09-04 21:30
Very good job.  Everything seems work properly.

THANKS

In attach the log.

https://www.dropbox.com/s/suy3melci3836ku/Proot_Debug_Log.txt0?dl=0
https://www.dropbox.com/s/au73d6vv99fnpf8/Proot_Debug_Log.txt1?dl=0

**Comment by corbinlc** [comment] 2019-09-04 21:32
Yes! Can you try Kali vs Ubuntu?  Can you also try SSH vs VNC?  I don't need logs for all of that, if it is all working.  I will start cleaning up what I did and prepping a public release.
Thanks so much!  Thanks to @x2slasher as well!

**Comment by corbinlc** [comment] 2019-09-04 21:35
The logs look good.  Looks like the last fix is doing the correct thing.

**Comment by paoloperissin** [comment] 2019-09-04 21:43
I have tried Kali and Ubuntu with both SSH and VNC and everything seems to be OK

As soon as you have finish the public release I'll test it and I'll inform you about the result

**Comment by corbinlc** [comment] 2019-09-04 21:46
For future reference, the issue was what was thought, the result needed to restored earlier to avoid PRoot reading memory that didn't belong to it.  The specific case was an `execve` system call.  In that case, if the system call result is not negative on exit PRoot tried to modify some things in memory as if the `execve` call had succeeded...but it hadn't.  I am not sure what other system calls would be caught by this same issue, but the solution I provided was generic to any system call.

**Comment by corbinlc** [comment] 2019-09-04 23:07
@paoloperissin and @x2slasher I pushed out this beta release: `2.6.3-beta-829014 `.  It will probably take a few hours to show up everywhere.  You have to opt-in to get the beta version of the app.

**Comment by corbinlc** [comment] 2019-09-04 23:08
Please confirm that you see this fixed, once you are able to download that version of the app.

**Closed by corbinlc** 2019-09-04 23:07 UTC

**Comment by paoloperissin** [comment] 2019-09-05 08:11
I have install the new version from the store. Everything us OK

THANKS AGAIN

**Comment by corbinlc** [comment] 2019-10-10 15:37
@paoloperissin  and @x2slasher can I bother you two again?  The fix I made which allowed you to continue was not robust enough for all users of armhf devices getting newer version of Android.  A potentially more robust solution has been put in place and I want to make sure it doesn't break you.  

Can you try this out and provide another PRoot log if it does not work?
Please uninstall the previous version first. <- hopefully it is not hard to get back any work you previously did.

https://github.com/CypherpunkArmory/UserLAnd/releases/download/proot-chdir/app-debug.apk

Thanks!
