### ISSUE TITLE
Zsync not working

### ISSUE THREAD

**Issue by Lokawn** [CypherpunkArmory/UserLAnd#305] opened 2018-10-05 14:18 UTC
While using zsync it gives following error
```
User@localhost:~$ zsync -i xubuntu-18.10-beta-desktop-amd64.iso    http://www.mirrorservice.org/sites/cdimage.ubuntu.com/cdimage/xubuntu/daily-live/current/cosmic-desktop-amd64.iso.zsync                                 

www.mirrorservice.org: No such file or directory
failed on url http://www.mirrorservice.org/sites/cdimage.ubuntu.com/cdimage/xubuntu/daily-live/current/cosmic-desktop-amd64.iso.zsync
could not read control file from URL http://www.mirrorservice.org/sites/cdimage.ubuntu.com/cdimage/xubuntu/daily-live/current/cosmic-desktop-amd64.iso.zsync
```
 Device- Moto G5 Plus
Android Oreo 8.1
App Version 0.4.0

**Comment by corbinlc** [comment] 2018-10-19 21:47
Interesting.  I have never used zsync.  Can you install `wget` and try to wget that file?

**Comment by Lokawn** [comment] 2018-10-20 00:07
Yes wget is working.

**Comment by AdamMatthewLTM** [comment] 2018-11-07 16:30
@Lokawn ,

Since I can confirm zsync-curl works, and wget is a standard which can be used as an alternative to zsync, I'm going to close this thread. If you (or anyone else) wants us to debug specifically why zsync is throwing that file not found error, please let me know and I'll take a look at it when I can. It will likely be a lower priority debug issue though, since no users have reported issues with wget.

Thanks for your time and patience,
-Adam

**Closed by AdamMatthewLTM** 2018-11-07 16:30 UTC
