### ISSUE TITLE
New request

### ISSUE THREAD

**Issue by wyssdbd** [CypherpunkArmory/UserLAnd#768] opened 2019-04-14 09:59 UTC
want to add eclipse to this project

**Comment by Marcus0086** [comment] 2019-04-14 17:31
I've already opened this issue 2 months ago. It seems that eclipse is only available for x86 and x64 architecture and in order to get it to work we have to emulate the whole environment for it by qemu and even if u make some success in emulation there is no way that it will work without any hassle as we know that even in native eclipse environment there are some lags. But i am not saying it is not possible I'm just stating that i will require much work than even the whole chroot system itself as getting working qemu in userland  then building eclipse environment then choosing best desktop environment for its use then bla bla bla more other things.

**Comment by EnderNightLord-ChromeBook** [comment] 2019-04-15 00:35
ooof.... I forgot about dat.

**Comment by corbinlc** [comment] 2019-04-16 16:27
This is a duplicate of #556.  As such, I am closing it.  Any progress made will be reported on that issue.

**Closed by corbinlc** 2019-04-16 16:27 UTC
Labels: more-info-required
