### ISSUE TITLE
/proc/version unaccessible (and therefore Libreoffice not working)

### ISSUE THREAD

**Issue by planck2007** [CypherpunkArmory/UserLAnd#92] opened 2018-07-12 20:20 UTC
The file /proc/version is unaccessible even by root. When running
`ls -l /proc/version I`
one obtains:
`-?????????   ? ?    ?     ?    ? version`
As a result Libreoffice doesn't run. In fact Libreoffice accesses /proc/version at startup and in this case fails and exits

My installation is on Samsung Galaxy Tab S3 with Android Oreo. 

Aniello

**Comment by AdamMatthewLTM** [comment] 2018-07-19 16:19
@planck2007 ,

My apologies for the late response. I have successfully been able to get LibreOffice open and working on older android versions, which leads me to believe that this is likely still a version issue. 

While I am not going to suggest immediately marking them as duplicates to this issue, I will reference #59 and #62 in relation to this. However, because this does seem to be a permissions issue I will mark it as high priority.

If I find a workaround specifically for LibreOffice, I will go ahead and post it here ASAP. Thank you for your patience and understanding,
-Adam

**Comment by planck2007** [comment] 2018-07-19 19:14
Thanks Adam, thanks for your work

In data 19 Luglio 2018 18:19:59 AdamMatthewLTM <notifications@github.com> 
ha scritto:

**Comment by Root-voidX** [comment] 2018-08-04 03:56
Yes i can confirm that on android 8.0 most things requiring proc, data and other directories cannot run due to permission issues. This was supposedly fixed with seccomp filter issues for proot but with newer kernals (i.e. new SD845 devices) the issue comes back. Maybe something changed that causes current syscalls to fail?

**Comment by corbinlc** [comment] 2018-08-04 15:52
We have not fixed the /proc issues for any 8.0+ devices yet.  This is not specific to device type.

**Comment by corbinlc** [comment] 2018-08-15 04:46
Closing this, please see #173 .  I am going to take a crack at fixing all of these next week and you an track that progress there.

**Closed by corbinlc** 2018-08-15 04:46 UTC
