### ISSUE TITLE
Is writing to external SD enabled ?

### ISSUE THREAD

**Issue by freebrowser1** [CypherpunkArmory/UserLAnd#70] opened 2018-06-29 09:04 UTC
For most Android devices there is an external SD card (/storage/XXXX-XXXX where X is a hexstring) which is normally not write enabled for apps.
Can UserLand enable WRITE_EXTERNAL, which would be useful for write accessing media, such as videos, from Userland ?

**Comment by DeicPro** [comment] 2018-07-03 23:47
Did you try to access through `host-rootfs` (is a bind to Android rootfs) folder. For example:
If SD Card path is `/storage/sdcard02`, then `/host-rootfs/storage/sdcard02` is the place.

You can type `env | grep 
STORAGE` in an Android terminal emulator to check exactly the correct path of both internal and external "SD"

**Comment by corbinlc** [comment] 2018-07-18 21:39
This is a duplicate of #46 

I can confirm that the fix for this will make it into the next release.  Specifically, you will be able to see your sdcard from inside your rootfs at the bound path /sdcard

**Closed** 2018-07-27 20:39 UTC
Labels: duplicate

**Comment by muehlber** [comment] 2018-08-01 15:41
I don't think this works in 0.2.3 yet, re #46 .

I can access shared internal storage via /sdcard but for external storage I still have to go via /host-rootfs/storage/<sdcardname>; and there I have only read access. Is there a way to give UserLAnd write access?

**Comment by Lokawn** [comment] 2018-08-13 15:17
I too can read External Storage but gives Permission denied error when I try to Write to external card.
Userland app version : 0.2.5
Filesystem : Ubuntu
Android Version : 7.0.0
Device is not rooted.

**Comment by bricolodu13** [comment] 2019-10-29 10:51
Hello all,

I have two Android phones
One is running Android 6.0 and can access the SDCard from within UserLand Debian in root mode with ln -s /host-rootfs/sdcard /

The second one is running Android 8.1.0 and CANNOT access the SDCard from within UserLand Debian in root mode. The same command ln -s /host-rootfs/sdcard / return premission denied

I also tried under root permission (sudo su) to change the repertory rights with chmod -R 777 /host-rootfs and I got :
chmod : changing permissions of '/host-rootfs': Read-only file system
chmod : cannot read directory '/host-rootfs': Permission denied

While the same command work on Android 6.0

Please help as my Android phone 6.0 has issues and I would like to use my new phone.
Best regards,
Jean

**Comment by ytrezq** [comment] 2019-12-20 00:21
@corbinlc NOT A DUPLICATE!

`/sdcard` is internal storage on android and is not about external usb or external sdcard. Se https://www.instructables.com/id/How-to-bypass-Android-44-KitKat-external-SD-write-/
