### ISSUE TITLE
Bug report - Failing tests on Windows

### ISSUE THREAD

**Issue by rhlobo** [CypherpunkArmory/UserLAnd#950] opened 2019-07-21 08:35 UTC
# Describe the bug

**Several unit tests fail under Windows.**
Not an app bug, but an development issue.

```
    > Task :app:testBetaUnitTest

    tech.ula.utils.BusyboxExecutorTest > Successfully executes 'scripts', using BusyboxWrapper#wrapScript FAILED
        java.lang.AssertionError at BusyboxExecutorTest.kt:150

    tech.ula.utils.BusyboxExecutorTest > Recursively deletes files FAILED
        java.lang.AssertionError at BusyboxExecutorTest.kt:283

    tech.ula.utils.BusyboxExecutorTest > Calling recursivelyDelete on a single file also works FAILED
        java.lang.AssertionError at BusyboxExecutorTest.kt:308

    tech.ula.utils.BusyboxExecutorTest > Successfully executes legal commands, 'adding' busybox FAILED
        java.lang.AssertionError at BusyboxExecutorTest.kt:112

    tech.ula.utils.BusyboxExecutorTest > Returns an OngoingExecution result with process if command should not terminate FAILED
        java.lang.AssertionError at BusyboxExecutorTest.kt:188

    tech.ula.utils.BusyboxExecutorTest > Successfully executes legal commands, 'adding' proot and busybox FAILED
        java.lang.AssertionError at BusyboxExecutorTest.kt:169

    tech.ula.utils.BusyboxExecutorTest > recursivelyDelete does not follow symbolic links FAILED
        java.nio.file.FileSystemException at BusyboxExecutorTest.kt:328

    tech.ula.utils.BusyboxExecutorTest > Calls ProotDebugLogger#logStream if logging is enabled FAILED
        java.lang.AssertionError at BusyboxExecutorTest.kt:216

    tech.ula.utils.FilesystemManagerTest > compressFilesystem logs failures FAILED
        java.lang.AssertionError at FilesystemManagerTest.kt:170

    tech.ula.utils.FilesystemManagerTest > compressFilesystem uses correct command and environment FAILED
        org.mockito.exceptions.verification.junit.ArgumentsAreDifferent at FilesystemManagerTest.kt:135

    tech.ula.utils.UlaFilesTest > Initialization links every file in the lib directory to support, stripping unnecessary name parts FAILED
        java.nio.file.FileSystemException at UlaFilesTest.kt:76

    tech.ula.utils.UlaFilesTest > makePermissionsUsable sets permissions open FAILED
        java.io.IOException at UlaFilesTest.kt:43
            Caused by: java.io.IOException at UlaFilesTest.kt:43

    293 tests completed, 12 failed

    > Task :app:testBetaUnitTest FAILED

    FAILURE: Build failed with an exception.
```

# Steps to reproduce the behavior:

On Windows, on Android Studio, run `gradlew testAll`

# Screenshots

n/a

# Device Information

OS: Windows 10
IDE: Android Studio 3.4.1;
Virtual Device: Nexus 5; Android Version 9.0

Does not seem to be an specific branch or commit issue, but:
Branch: Master
Commit: b2eccba37e59dfd7455abef9aafda80eea8ae91b

**Comment by MatthewTighe** [comment] 2019-07-22 16:12
Have you edited those files at all? Need to know if the line numbers match the repo

**Comment by rhlobo** [comment] 2019-07-22 19:58
Not edited at all. The whole project matches the repo.
Any other information you need?

**Comment by MatthewTighe** [comment] 2019-07-22 20:19
It's unsurprising that all those tests fail on Windows because they are all tests verifying expected Unix behavior. Windows processes naturally wouldn't have access to commands like `echo` and `chmod`, and they don't handle permissions the same way. Since those are unit tests, they are meant to be run in the development environment directly for maximum speed, _not_ on Android for example. The only weird failure is `FilesystemManager`, but without access to a Windows dev environment it's hard for me to verify why it's failing. The test still passes on a Unix-like machine and will pass our CI/CD pipeline.

I think the easiest thing to do would just be to ignore those failures. You may have a hard time writing unit tests for the feature you're looking to implement, but we can cross that bridge when we come to it.
I also don't think it's worth implementing either:
1. A workaround for windows to ignore tests since it weakens regression.
2. Windows-specific implementations of the tests, since they are meant to verify Unix-like behavior.

I'm going to close this issue because I actually think this is a feature now that you bring it up- it's a way to help Windows users become aware of this situation.

**Closed by MatthewTighe** 2019-07-22 20:19 UTC

**Comment by rhlobo** [comment] 2019-07-22 21:36
Ok, thx

**Comment by rhlobo** [comment] 2019-07-22 21:46
Would add a "assume" before these tests weaken regression?

@Before
 public void beforeMethod() {
     org.junit.Assume.assumeTrue(someCondition());
     // rest of setup.
 }

Tests would be then ignored when condition is not met.
Well, up to you.
